// Code generated by protoc-gen-go. DO NOT EDIT.
// source: spacemesh/v1/global_state_types.proto

package spacemesh_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// All data items that touch an account (see below note, under the associated
// message)
type AccountDataFlag int32

const (
	AccountDataFlag_ACCOUNT_DATA_FLAG_UNSPECIFIED         AccountDataFlag = 0
	AccountDataFlag_ACCOUNT_DATA_FLAG_TRANSACTION_RECEIPT AccountDataFlag = 1
	AccountDataFlag_ACCOUNT_DATA_FLAG_REWARD              AccountDataFlag = 2
	AccountDataFlag_ACCOUNT_DATA_FLAG_ACCOUNT             AccountDataFlag = 4
)

var AccountDataFlag_name = map[int32]string{
	0: "ACCOUNT_DATA_FLAG_UNSPECIFIED",
	1: "ACCOUNT_DATA_FLAG_TRANSACTION_RECEIPT",
	2: "ACCOUNT_DATA_FLAG_REWARD",
	4: "ACCOUNT_DATA_FLAG_ACCOUNT",
}

var AccountDataFlag_value = map[string]int32{
	"ACCOUNT_DATA_FLAG_UNSPECIFIED":         0,
	"ACCOUNT_DATA_FLAG_TRANSACTION_RECEIPT": 1,
	"ACCOUNT_DATA_FLAG_REWARD":              2,
	"ACCOUNT_DATA_FLAG_ACCOUNT":             4,
}

func (x AccountDataFlag) String() string {
	return proto.EnumName(AccountDataFlag_name, int32(x))
}

func (AccountDataFlag) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8a3fff2434f8a73d, []int{0}
}

type GlobalStateDataItemFlag int32

const (
	GlobalStateDataItemFlag_GLOBAL_STATE_DATA_ITEM_FLAG_UNSPECIFIED         GlobalStateDataItemFlag = 0
	GlobalStateDataItemFlag_GLOBAL_STATE_DATA_ITEM_FLAG_TRANSACTION_RECEIPT GlobalStateDataItemFlag = 1
	GlobalStateDataItemFlag_GLOBAL_STATE_DATA_ITEM_FLAG_REWARD              GlobalStateDataItemFlag = 2
	GlobalStateDataItemFlag_GLOBAL_STATE_DATA_ITEM_FLAG_ACCOUNT             GlobalStateDataItemFlag = 4
	GlobalStateDataItemFlag_GLOBAL_STATE_DATA_ITEM_FLAG_GLOBAL_STATE_HASH   GlobalStateDataItemFlag = 8
)

var GlobalStateDataItemFlag_name = map[int32]string{
	0: "GLOBAL_STATE_DATA_ITEM_FLAG_UNSPECIFIED",
	1: "GLOBAL_STATE_DATA_ITEM_FLAG_TRANSACTION_RECEIPT",
	2: "GLOBAL_STATE_DATA_ITEM_FLAG_REWARD",
	4: "GLOBAL_STATE_DATA_ITEM_FLAG_ACCOUNT",
	8: "GLOBAL_STATE_DATA_ITEM_FLAG_GLOBAL_STATE_HASH",
}

var GlobalStateDataItemFlag_value = map[string]int32{
	"GLOBAL_STATE_DATA_ITEM_FLAG_UNSPECIFIED":         0,
	"GLOBAL_STATE_DATA_ITEM_FLAG_TRANSACTION_RECEIPT": 1,
	"GLOBAL_STATE_DATA_ITEM_FLAG_REWARD":              2,
	"GLOBAL_STATE_DATA_ITEM_FLAG_ACCOUNT":             4,
	"GLOBAL_STATE_DATA_ITEM_FLAG_GLOBAL_STATE_HASH":   8,
}

func (x GlobalStateDataItemFlag) String() string {
	return proto.EnumName(GlobalStateDataItemFlag_name, int32(x))
}

func (GlobalStateDataItemFlag) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8a3fff2434f8a73d, []int{1}
}

type AccountRequest struct {
	AccountId            *AccountId `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AccountRequest) Reset()         { *m = AccountRequest{} }
func (m *AccountRequest) String() string { return proto.CompactTextString(m) }
func (*AccountRequest) ProtoMessage()    {}
func (*AccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a3fff2434f8a73d, []int{0}
}

func (m *AccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountRequest.Unmarshal(m, b)
}
func (m *AccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountRequest.Marshal(b, m, deterministic)
}
func (m *AccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountRequest.Merge(m, src)
}
func (m *AccountRequest) XXX_Size() int {
	return xxx_messageInfo_AccountRequest.Size(m)
}
func (m *AccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountRequest proto.InternalMessageInfo

func (m *AccountRequest) GetAccountId() *AccountId {
	if m != nil {
		return m.AccountId
	}
	return nil
}

type AccountResponse struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountResponse) Reset()         { *m = AccountResponse{} }
func (m *AccountResponse) String() string { return proto.CompactTextString(m) }
func (*AccountResponse) ProtoMessage()    {}
func (*AccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a3fff2434f8a73d, []int{1}
}

func (m *AccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountResponse.Unmarshal(m, b)
}
func (m *AccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountResponse.Marshal(b, m, deterministic)
}
func (m *AccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountResponse.Merge(m, src)
}
func (m *AccountResponse) XXX_Size() int {
	return xxx_messageInfo_AccountResponse.Size(m)
}
func (m *AccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AccountResponse proto.InternalMessageInfo

func (m *AccountResponse) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type AccountDataFilter struct {
	AccountId            *AccountId `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AccountDataFlags     uint32     `protobuf:"varint,2,opt,name=account_data_flags,json=accountDataFlags,proto3" json:"account_data_flags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AccountDataFilter) Reset()         { *m = AccountDataFilter{} }
func (m *AccountDataFilter) String() string { return proto.CompactTextString(m) }
func (*AccountDataFilter) ProtoMessage()    {}
func (*AccountDataFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a3fff2434f8a73d, []int{2}
}

func (m *AccountDataFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountDataFilter.Unmarshal(m, b)
}
func (m *AccountDataFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountDataFilter.Marshal(b, m, deterministic)
}
func (m *AccountDataFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountDataFilter.Merge(m, src)
}
func (m *AccountDataFilter) XXX_Size() int {
	return xxx_messageInfo_AccountDataFilter.Size(m)
}
func (m *AccountDataFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountDataFilter.DiscardUnknown(m)
}

var xxx_messageInfo_AccountDataFilter proto.InternalMessageInfo

func (m *AccountDataFilter) GetAccountId() *AccountId {
	if m != nil {
		return m.AccountId
	}
	return nil
}

func (m *AccountDataFilter) GetAccountDataFlags() uint32 {
	if m != nil {
		return m.AccountDataFlags
	}
	return 0
}

type AccountDataStreamRequest struct {
	Filter               *AccountDataFilter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *AccountDataStreamRequest) Reset()         { *m = AccountDataStreamRequest{} }
func (m *AccountDataStreamRequest) String() string { return proto.CompactTextString(m) }
func (*AccountDataStreamRequest) ProtoMessage()    {}
func (*AccountDataStreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a3fff2434f8a73d, []int{3}
}

func (m *AccountDataStreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountDataStreamRequest.Unmarshal(m, b)
}
func (m *AccountDataStreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountDataStreamRequest.Marshal(b, m, deterministic)
}
func (m *AccountDataStreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountDataStreamRequest.Merge(m, src)
}
func (m *AccountDataStreamRequest) XXX_Size() int {
	return xxx_messageInfo_AccountDataStreamRequest.Size(m)
}
func (m *AccountDataStreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountDataStreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountDataStreamRequest proto.InternalMessageInfo

func (m *AccountDataStreamRequest) GetFilter() *AccountDataFilter {
	if m != nil {
		return m.Filter
	}
	return nil
}

type AccountDataStreamResponse struct {
	Data                 *AccountData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AccountDataStreamResponse) Reset()         { *m = AccountDataStreamResponse{} }
func (m *AccountDataStreamResponse) String() string { return proto.CompactTextString(m) }
func (*AccountDataStreamResponse) ProtoMessage()    {}
func (*AccountDataStreamResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a3fff2434f8a73d, []int{4}
}

func (m *AccountDataStreamResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountDataStreamResponse.Unmarshal(m, b)
}
func (m *AccountDataStreamResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountDataStreamResponse.Marshal(b, m, deterministic)
}
func (m *AccountDataStreamResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountDataStreamResponse.Merge(m, src)
}
func (m *AccountDataStreamResponse) XXX_Size() int {
	return xxx_messageInfo_AccountDataStreamResponse.Size(m)
}
func (m *AccountDataStreamResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountDataStreamResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AccountDataStreamResponse proto.InternalMessageInfo

func (m *AccountDataStreamResponse) GetData() *AccountData {
	if m != nil {
		return m.Data
	}
	return nil
}

type AccountDataQueryRequest struct {
	Filter               *AccountDataFilter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	MaxResults           uint32             `protobuf:"varint,2,opt,name=max_results,json=maxResults,proto3" json:"max_results,omitempty"`
	Offset               uint32             `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *AccountDataQueryRequest) Reset()         { *m = AccountDataQueryRequest{} }
func (m *AccountDataQueryRequest) String() string { return proto.CompactTextString(m) }
func (*AccountDataQueryRequest) ProtoMessage()    {}
func (*AccountDataQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a3fff2434f8a73d, []int{5}
}

func (m *AccountDataQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountDataQueryRequest.Unmarshal(m, b)
}
func (m *AccountDataQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountDataQueryRequest.Marshal(b, m, deterministic)
}
func (m *AccountDataQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountDataQueryRequest.Merge(m, src)
}
func (m *AccountDataQueryRequest) XXX_Size() int {
	return xxx_messageInfo_AccountDataQueryRequest.Size(m)
}
func (m *AccountDataQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountDataQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountDataQueryRequest proto.InternalMessageInfo

func (m *AccountDataQueryRequest) GetFilter() *AccountDataFilter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *AccountDataQueryRequest) GetMaxResults() uint32 {
	if m != nil {
		return m.MaxResults
	}
	return 0
}

func (m *AccountDataQueryRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

// All data items that touch an account: receipts for transactions from, or to
// this account, as well as those that modify its state (e.g., token transfers).
// Rewards here includes fees paid. Account contains counter and balance updates.
// Note that this mixes concerns: transactions and rewards are _causes_ of a
// change to account state; nonce and balance updates are _results_.
type AccountData struct {
	// Types that are valid to be assigned to Item:
	//	*AccountData_Reward
	//	*AccountData_Receipt
	//	*AccountData_Account
	Item                 isAccountData_Item `protobuf_oneof:"item"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *AccountData) Reset()         { *m = AccountData{} }
func (m *AccountData) String() string { return proto.CompactTextString(m) }
func (*AccountData) ProtoMessage()    {}
func (*AccountData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a3fff2434f8a73d, []int{6}
}

func (m *AccountData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountData.Unmarshal(m, b)
}
func (m *AccountData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountData.Marshal(b, m, deterministic)
}
func (m *AccountData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountData.Merge(m, src)
}
func (m *AccountData) XXX_Size() int {
	return xxx_messageInfo_AccountData.Size(m)
}
func (m *AccountData) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountData.DiscardUnknown(m)
}

var xxx_messageInfo_AccountData proto.InternalMessageInfo

type isAccountData_Item interface {
	isAccountData_Item()
}

type AccountData_Reward struct {
	Reward *Reward `protobuf:"bytes,1,opt,name=reward,proto3,oneof"`
}

type AccountData_Receipt struct {
	Receipt *TransactionReceipt `protobuf:"bytes,2,opt,name=receipt,proto3,oneof"`
}

type AccountData_Account struct {
	Account *Account `protobuf:"bytes,3,opt,name=account,proto3,oneof"`
}

func (*AccountData_Reward) isAccountData_Item() {}

func (*AccountData_Receipt) isAccountData_Item() {}

func (*AccountData_Account) isAccountData_Item() {}

func (m *AccountData) GetItem() isAccountData_Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *AccountData) GetReward() *Reward {
	if x, ok := m.GetItem().(*AccountData_Reward); ok {
		return x.Reward
	}
	return nil
}

func (m *AccountData) GetReceipt() *TransactionReceipt {
	if x, ok := m.GetItem().(*AccountData_Receipt); ok {
		return x.Receipt
	}
	return nil
}

func (m *AccountData) GetAccount() *Account {
	if x, ok := m.GetItem().(*AccountData_Account); ok {
		return x.Account
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*AccountData) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*AccountData_Reward)(nil),
		(*AccountData_Receipt)(nil),
		(*AccountData_Account)(nil),
	}
}

type AccountDataQueryResponse struct {
	TotalResults         uint32         `protobuf:"varint,1,opt,name=total_results,json=totalResults,proto3" json:"total_results,omitempty"`
	AccountItem          []*AccountData `protobuf:"bytes,2,rep,name=account_item,json=accountItem,proto3" json:"account_item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AccountDataQueryResponse) Reset()         { *m = AccountDataQueryResponse{} }
func (m *AccountDataQueryResponse) String() string { return proto.CompactTextString(m) }
func (*AccountDataQueryResponse) ProtoMessage()    {}
func (*AccountDataQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a3fff2434f8a73d, []int{7}
}

func (m *AccountDataQueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountDataQueryResponse.Unmarshal(m, b)
}
func (m *AccountDataQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountDataQueryResponse.Marshal(b, m, deterministic)
}
func (m *AccountDataQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountDataQueryResponse.Merge(m, src)
}
func (m *AccountDataQueryResponse) XXX_Size() int {
	return xxx_messageInfo_AccountDataQueryResponse.Size(m)
}
func (m *AccountDataQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountDataQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AccountDataQueryResponse proto.InternalMessageInfo

func (m *AccountDataQueryResponse) GetTotalResults() uint32 {
	if m != nil {
		return m.TotalResults
	}
	return 0
}

func (m *AccountDataQueryResponse) GetAccountItem() []*AccountData {
	if m != nil {
		return m.AccountItem
	}
	return nil
}

type SmesherRewardStreamRequest struct {
	Id                   *SmesherId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SmesherRewardStreamRequest) Reset()         { *m = SmesherRewardStreamRequest{} }
func (m *SmesherRewardStreamRequest) String() string { return proto.CompactTextString(m) }
func (*SmesherRewardStreamRequest) ProtoMessage()    {}
func (*SmesherRewardStreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a3fff2434f8a73d, []int{8}
}

func (m *SmesherRewardStreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmesherRewardStreamRequest.Unmarshal(m, b)
}
func (m *SmesherRewardStreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmesherRewardStreamRequest.Marshal(b, m, deterministic)
}
func (m *SmesherRewardStreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmesherRewardStreamRequest.Merge(m, src)
}
func (m *SmesherRewardStreamRequest) XXX_Size() int {
	return xxx_messageInfo_SmesherRewardStreamRequest.Size(m)
}
func (m *SmesherRewardStreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SmesherRewardStreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SmesherRewardStreamRequest proto.InternalMessageInfo

func (m *SmesherRewardStreamRequest) GetId() *SmesherId {
	if m != nil {
		return m.Id
	}
	return nil
}

type SmesherRewardStreamResponse struct {
	Reward               *Reward  `protobuf:"bytes,1,opt,name=reward,proto3" json:"reward,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SmesherRewardStreamResponse) Reset()         { *m = SmesherRewardStreamResponse{} }
func (m *SmesherRewardStreamResponse) String() string { return proto.CompactTextString(m) }
func (*SmesherRewardStreamResponse) ProtoMessage()    {}
func (*SmesherRewardStreamResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a3fff2434f8a73d, []int{9}
}

func (m *SmesherRewardStreamResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmesherRewardStreamResponse.Unmarshal(m, b)
}
func (m *SmesherRewardStreamResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmesherRewardStreamResponse.Marshal(b, m, deterministic)
}
func (m *SmesherRewardStreamResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmesherRewardStreamResponse.Merge(m, src)
}
func (m *SmesherRewardStreamResponse) XXX_Size() int {
	return xxx_messageInfo_SmesherRewardStreamResponse.Size(m)
}
func (m *SmesherRewardStreamResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SmesherRewardStreamResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SmesherRewardStreamResponse proto.InternalMessageInfo

func (m *SmesherRewardStreamResponse) GetReward() *Reward {
	if m != nil {
		return m.Reward
	}
	return nil
}

type SmesherDataQueryRequest struct {
	SmesherId            *SmesherId `protobuf:"bytes,1,opt,name=smesher_id,json=smesherId,proto3" json:"smesher_id,omitempty"`
	MaxResults           uint32     `protobuf:"varint,2,opt,name=max_results,json=maxResults,proto3" json:"max_results,omitempty"`
	Offset               uint32     `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SmesherDataQueryRequest) Reset()         { *m = SmesherDataQueryRequest{} }
func (m *SmesherDataQueryRequest) String() string { return proto.CompactTextString(m) }
func (*SmesherDataQueryRequest) ProtoMessage()    {}
func (*SmesherDataQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a3fff2434f8a73d, []int{10}
}

func (m *SmesherDataQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmesherDataQueryRequest.Unmarshal(m, b)
}
func (m *SmesherDataQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmesherDataQueryRequest.Marshal(b, m, deterministic)
}
func (m *SmesherDataQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmesherDataQueryRequest.Merge(m, src)
}
func (m *SmesherDataQueryRequest) XXX_Size() int {
	return xxx_messageInfo_SmesherDataQueryRequest.Size(m)
}
func (m *SmesherDataQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SmesherDataQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SmesherDataQueryRequest proto.InternalMessageInfo

func (m *SmesherDataQueryRequest) GetSmesherId() *SmesherId {
	if m != nil {
		return m.SmesherId
	}
	return nil
}

func (m *SmesherDataQueryRequest) GetMaxResults() uint32 {
	if m != nil {
		return m.MaxResults
	}
	return 0
}

func (m *SmesherDataQueryRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type SmesherDataQueryResponse struct {
	TotalResults         uint32    `protobuf:"varint,1,opt,name=total_results,json=totalResults,proto3" json:"total_results,omitempty"`
	Rewards              []*Reward `protobuf:"bytes,2,rep,name=rewards,proto3" json:"rewards,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SmesherDataQueryResponse) Reset()         { *m = SmesherDataQueryResponse{} }
func (m *SmesherDataQueryResponse) String() string { return proto.CompactTextString(m) }
func (*SmesherDataQueryResponse) ProtoMessage()    {}
func (*SmesherDataQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a3fff2434f8a73d, []int{11}
}

func (m *SmesherDataQueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmesherDataQueryResponse.Unmarshal(m, b)
}
func (m *SmesherDataQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmesherDataQueryResponse.Marshal(b, m, deterministic)
}
func (m *SmesherDataQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmesherDataQueryResponse.Merge(m, src)
}
func (m *SmesherDataQueryResponse) XXX_Size() int {
	return xxx_messageInfo_SmesherDataQueryResponse.Size(m)
}
func (m *SmesherDataQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SmesherDataQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SmesherDataQueryResponse proto.InternalMessageInfo

func (m *SmesherDataQueryResponse) GetTotalResults() uint32 {
	if m != nil {
		return m.TotalResults
	}
	return 0
}

func (m *SmesherDataQueryResponse) GetRewards() []*Reward {
	if m != nil {
		return m.Rewards
	}
	return nil
}

type GlobalStateHash struct {
	RootHash             []byte   `protobuf:"bytes,1,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
	LayerNumber          uint64   `protobuf:"varint,2,opt,name=layer_number,json=layerNumber,proto3" json:"layer_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GlobalStateHash) Reset()         { *m = GlobalStateHash{} }
func (m *GlobalStateHash) String() string { return proto.CompactTextString(m) }
func (*GlobalStateHash) ProtoMessage()    {}
func (*GlobalStateHash) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a3fff2434f8a73d, []int{12}
}

func (m *GlobalStateHash) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GlobalStateHash.Unmarshal(m, b)
}
func (m *GlobalStateHash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GlobalStateHash.Marshal(b, m, deterministic)
}
func (m *GlobalStateHash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GlobalStateHash.Merge(m, src)
}
func (m *GlobalStateHash) XXX_Size() int {
	return xxx_messageInfo_GlobalStateHash.Size(m)
}
func (m *GlobalStateHash) XXX_DiscardUnknown() {
	xxx_messageInfo_GlobalStateHash.DiscardUnknown(m)
}

var xxx_messageInfo_GlobalStateHash proto.InternalMessageInfo

func (m *GlobalStateHash) GetRootHash() []byte {
	if m != nil {
		return m.RootHash
	}
	return nil
}

func (m *GlobalStateHash) GetLayerNumber() uint64 {
	if m != nil {
		return m.LayerNumber
	}
	return 0
}

// For now this is empty but in future we might want to allow this to take a
// layer number.
type GlobalStateHashRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GlobalStateHashRequest) Reset()         { *m = GlobalStateHashRequest{} }
func (m *GlobalStateHashRequest) String() string { return proto.CompactTextString(m) }
func (*GlobalStateHashRequest) ProtoMessage()    {}
func (*GlobalStateHashRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a3fff2434f8a73d, []int{13}
}

func (m *GlobalStateHashRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GlobalStateHashRequest.Unmarshal(m, b)
}
func (m *GlobalStateHashRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GlobalStateHashRequest.Marshal(b, m, deterministic)
}
func (m *GlobalStateHashRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GlobalStateHashRequest.Merge(m, src)
}
func (m *GlobalStateHashRequest) XXX_Size() int {
	return xxx_messageInfo_GlobalStateHashRequest.Size(m)
}
func (m *GlobalStateHashRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GlobalStateHashRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GlobalStateHashRequest proto.InternalMessageInfo

type GlobalStateHashResponse struct {
	Response             *GlobalStateHash `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GlobalStateHashResponse) Reset()         { *m = GlobalStateHashResponse{} }
func (m *GlobalStateHashResponse) String() string { return proto.CompactTextString(m) }
func (*GlobalStateHashResponse) ProtoMessage()    {}
func (*GlobalStateHashResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a3fff2434f8a73d, []int{14}
}

func (m *GlobalStateHashResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GlobalStateHashResponse.Unmarshal(m, b)
}
func (m *GlobalStateHashResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GlobalStateHashResponse.Marshal(b, m, deterministic)
}
func (m *GlobalStateHashResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GlobalStateHashResponse.Merge(m, src)
}
func (m *GlobalStateHashResponse) XXX_Size() int {
	return xxx_messageInfo_GlobalStateHashResponse.Size(m)
}
func (m *GlobalStateHashResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GlobalStateHashResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GlobalStateHashResponse proto.InternalMessageInfo

func (m *GlobalStateHashResponse) GetResponse() *GlobalStateHash {
	if m != nil {
		return m.Response
	}
	return nil
}

type GlobalStateStreamRequest struct {
	GlobalStateDataItemFlags uint32   `protobuf:"varint,1,opt,name=global_state_data_item_flags,json=globalStateDataItemFlags,proto3" json:"global_state_data_item_flags,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *GlobalStateStreamRequest) Reset()         { *m = GlobalStateStreamRequest{} }
func (m *GlobalStateStreamRequest) String() string { return proto.CompactTextString(m) }
func (*GlobalStateStreamRequest) ProtoMessage()    {}
func (*GlobalStateStreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a3fff2434f8a73d, []int{15}
}

func (m *GlobalStateStreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GlobalStateStreamRequest.Unmarshal(m, b)
}
func (m *GlobalStateStreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GlobalStateStreamRequest.Marshal(b, m, deterministic)
}
func (m *GlobalStateStreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GlobalStateStreamRequest.Merge(m, src)
}
func (m *GlobalStateStreamRequest) XXX_Size() int {
	return xxx_messageInfo_GlobalStateStreamRequest.Size(m)
}
func (m *GlobalStateStreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GlobalStateStreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GlobalStateStreamRequest proto.InternalMessageInfo

func (m *GlobalStateStreamRequest) GetGlobalStateDataItemFlags() uint32 {
	if m != nil {
		return m.GlobalStateDataItemFlags
	}
	return 0
}

type GlobalStateDataItem struct {
	// Types that are valid to be assigned to Data:
	//	*GlobalStateDataItem_Reward
	//	*GlobalStateDataItem_Receipt
	//	*GlobalStateDataItem_Account
	//	*GlobalStateDataItem_GlobalState
	Data                 isGlobalStateDataItem_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *GlobalStateDataItem) Reset()         { *m = GlobalStateDataItem{} }
func (m *GlobalStateDataItem) String() string { return proto.CompactTextString(m) }
func (*GlobalStateDataItem) ProtoMessage()    {}
func (*GlobalStateDataItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a3fff2434f8a73d, []int{16}
}

func (m *GlobalStateDataItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GlobalStateDataItem.Unmarshal(m, b)
}
func (m *GlobalStateDataItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GlobalStateDataItem.Marshal(b, m, deterministic)
}
func (m *GlobalStateDataItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GlobalStateDataItem.Merge(m, src)
}
func (m *GlobalStateDataItem) XXX_Size() int {
	return xxx_messageInfo_GlobalStateDataItem.Size(m)
}
func (m *GlobalStateDataItem) XXX_DiscardUnknown() {
	xxx_messageInfo_GlobalStateDataItem.DiscardUnknown(m)
}

var xxx_messageInfo_GlobalStateDataItem proto.InternalMessageInfo

type isGlobalStateDataItem_Data interface {
	isGlobalStateDataItem_Data()
}

type GlobalStateDataItem_Reward struct {
	Reward *Reward `protobuf:"bytes,1,opt,name=reward,proto3,oneof"`
}

type GlobalStateDataItem_Receipt struct {
	Receipt *TransactionReceipt `protobuf:"bytes,2,opt,name=receipt,proto3,oneof"`
}

type GlobalStateDataItem_Account struct {
	Account *Account `protobuf:"bytes,3,opt,name=account,proto3,oneof"`
}

type GlobalStateDataItem_GlobalState struct {
	GlobalState *GlobalStateHash `protobuf:"bytes,4,opt,name=global_state,json=globalState,proto3,oneof"`
}

func (*GlobalStateDataItem_Reward) isGlobalStateDataItem_Data() {}

func (*GlobalStateDataItem_Receipt) isGlobalStateDataItem_Data() {}

func (*GlobalStateDataItem_Account) isGlobalStateDataItem_Data() {}

func (*GlobalStateDataItem_GlobalState) isGlobalStateDataItem_Data() {}

func (m *GlobalStateDataItem) GetData() isGlobalStateDataItem_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GlobalStateDataItem) GetReward() *Reward {
	if x, ok := m.GetData().(*GlobalStateDataItem_Reward); ok {
		return x.Reward
	}
	return nil
}

func (m *GlobalStateDataItem) GetReceipt() *TransactionReceipt {
	if x, ok := m.GetData().(*GlobalStateDataItem_Receipt); ok {
		return x.Receipt
	}
	return nil
}

func (m *GlobalStateDataItem) GetAccount() *Account {
	if x, ok := m.GetData().(*GlobalStateDataItem_Account); ok {
		return x.Account
	}
	return nil
}

func (m *GlobalStateDataItem) GetGlobalState() *GlobalStateHash {
	if x, ok := m.GetData().(*GlobalStateDataItem_GlobalState); ok {
		return x.GlobalState
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GlobalStateDataItem) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GlobalStateDataItem_Reward)(nil),
		(*GlobalStateDataItem_Receipt)(nil),
		(*GlobalStateDataItem_Account)(nil),
		(*GlobalStateDataItem_GlobalState)(nil),
	}
}

type GlobalStateStreamResponse struct {
	DataItem             []*GlobalStateDataItem `protobuf:"bytes,1,rep,name=data_item,json=dataItem,proto3" json:"data_item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GlobalStateStreamResponse) Reset()         { *m = GlobalStateStreamResponse{} }
func (m *GlobalStateStreamResponse) String() string { return proto.CompactTextString(m) }
func (*GlobalStateStreamResponse) ProtoMessage()    {}
func (*GlobalStateStreamResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a3fff2434f8a73d, []int{17}
}

func (m *GlobalStateStreamResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GlobalStateStreamResponse.Unmarshal(m, b)
}
func (m *GlobalStateStreamResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GlobalStateStreamResponse.Marshal(b, m, deterministic)
}
func (m *GlobalStateStreamResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GlobalStateStreamResponse.Merge(m, src)
}
func (m *GlobalStateStreamResponse) XXX_Size() int {
	return xxx_messageInfo_GlobalStateStreamResponse.Size(m)
}
func (m *GlobalStateStreamResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GlobalStateStreamResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GlobalStateStreamResponse proto.InternalMessageInfo

func (m *GlobalStateStreamResponse) GetDataItem() []*GlobalStateDataItem {
	if m != nil {
		return m.DataItem
	}
	return nil
}

type AppEventStreamRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppEventStreamRequest) Reset()         { *m = AppEventStreamRequest{} }
func (m *AppEventStreamRequest) String() string { return proto.CompactTextString(m) }
func (*AppEventStreamRequest) ProtoMessage()    {}
func (*AppEventStreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a3fff2434f8a73d, []int{18}
}

func (m *AppEventStreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppEventStreamRequest.Unmarshal(m, b)
}
func (m *AppEventStreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppEventStreamRequest.Marshal(b, m, deterministic)
}
func (m *AppEventStreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppEventStreamRequest.Merge(m, src)
}
func (m *AppEventStreamRequest) XXX_Size() int {
	return xxx_messageInfo_AppEventStreamRequest.Size(m)
}
func (m *AppEventStreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AppEventStreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AppEventStreamRequest proto.InternalMessageInfo

type AppEventStreamResponse struct {
	Event                *AppEvent `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AppEventStreamResponse) Reset()         { *m = AppEventStreamResponse{} }
func (m *AppEventStreamResponse) String() string { return proto.CompactTextString(m) }
func (*AppEventStreamResponse) ProtoMessage()    {}
func (*AppEventStreamResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a3fff2434f8a73d, []int{19}
}

func (m *AppEventStreamResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppEventStreamResponse.Unmarshal(m, b)
}
func (m *AppEventStreamResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppEventStreamResponse.Marshal(b, m, deterministic)
}
func (m *AppEventStreamResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppEventStreamResponse.Merge(m, src)
}
func (m *AppEventStreamResponse) XXX_Size() int {
	return xxx_messageInfo_AppEventStreamResponse.Size(m)
}
func (m *AppEventStreamResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AppEventStreamResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AppEventStreamResponse proto.InternalMessageInfo

func (m *AppEventStreamResponse) GetEvent() *AppEvent {
	if m != nil {
		return m.Event
	}
	return nil
}

func init() {
	proto.RegisterEnum("spacemesh.v1.AccountDataFlag", AccountDataFlag_name, AccountDataFlag_value)
	proto.RegisterEnum("spacemesh.v1.GlobalStateDataItemFlag", GlobalStateDataItemFlag_name, GlobalStateDataItemFlag_value)
	proto.RegisterType((*AccountRequest)(nil), "spacemesh.v1.AccountRequest")
	proto.RegisterType((*AccountResponse)(nil), "spacemesh.v1.AccountResponse")
	proto.RegisterType((*AccountDataFilter)(nil), "spacemesh.v1.AccountDataFilter")
	proto.RegisterType((*AccountDataStreamRequest)(nil), "spacemesh.v1.AccountDataStreamRequest")
	proto.RegisterType((*AccountDataStreamResponse)(nil), "spacemesh.v1.AccountDataStreamResponse")
	proto.RegisterType((*AccountDataQueryRequest)(nil), "spacemesh.v1.AccountDataQueryRequest")
	proto.RegisterType((*AccountData)(nil), "spacemesh.v1.AccountData")
	proto.RegisterType((*AccountDataQueryResponse)(nil), "spacemesh.v1.AccountDataQueryResponse")
	proto.RegisterType((*SmesherRewardStreamRequest)(nil), "spacemesh.v1.SmesherRewardStreamRequest")
	proto.RegisterType((*SmesherRewardStreamResponse)(nil), "spacemesh.v1.SmesherRewardStreamResponse")
	proto.RegisterType((*SmesherDataQueryRequest)(nil), "spacemesh.v1.SmesherDataQueryRequest")
	proto.RegisterType((*SmesherDataQueryResponse)(nil), "spacemesh.v1.SmesherDataQueryResponse")
	proto.RegisterType((*GlobalStateHash)(nil), "spacemesh.v1.GlobalStateHash")
	proto.RegisterType((*GlobalStateHashRequest)(nil), "spacemesh.v1.GlobalStateHashRequest")
	proto.RegisterType((*GlobalStateHashResponse)(nil), "spacemesh.v1.GlobalStateHashResponse")
	proto.RegisterType((*GlobalStateStreamRequest)(nil), "spacemesh.v1.GlobalStateStreamRequest")
	proto.RegisterType((*GlobalStateDataItem)(nil), "spacemesh.v1.GlobalStateDataItem")
	proto.RegisterType((*GlobalStateStreamResponse)(nil), "spacemesh.v1.GlobalStateStreamResponse")
	proto.RegisterType((*AppEventStreamRequest)(nil), "spacemesh.v1.AppEventStreamRequest")
	proto.RegisterType((*AppEventStreamResponse)(nil), "spacemesh.v1.AppEventStreamResponse")
}

func init() {
	proto.RegisterFile("spacemesh/v1/global_state_types.proto", fileDescriptor_8a3fff2434f8a73d)
}

var fileDescriptor_8a3fff2434f8a73d = []byte{
	// 862 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0xdd, 0x8e, 0xda, 0x46,
	0x14, 0x5e, 0xb3, 0x94, 0xec, 0x1e, 0x48, 0x43, 0xa7, 0x0d, 0x98, 0x24, 0xab, 0xb0, 0x13, 0xa5,
	0x9b, 0xa6, 0x09, 0x88, 0x44, 0x4a, 0x55, 0x29, 0x8a, 0x64, 0xc0, 0xfc, 0xb4, 0x5b, 0x36, 0x19,
	0x3b, 0xaa, 0xd4, 0x5e, 0x58, 0xb3, 0x30, 0x2c, 0x48, 0x80, 0xa9, 0x67, 0xd8, 0x86, 0x8b, 0xde,
	0xf4, 0xb2, 0x7d, 0x85, 0x3e, 0x47, 0x5f, 0xaf, 0x95, 0xc7, 0x63, 0xaf, 0x0d, 0x5e, 0x9a, 0xa6,
	0x37, 0xbd, 0x33, 0xe7, 0x7c, 0xe7, 0xef, 0x3b, 0x9f, 0x8f, 0x81, 0x87, 0x7c, 0x49, 0x87, 0x6c,
	0xce, 0xf8, 0xa4, 0x7e, 0xd9, 0xa8, 0x5f, 0xcc, 0xdc, 0x73, 0x3a, 0x73, 0xb8, 0xa0, 0x82, 0x39,
	0x62, 0xbd, 0x64, 0xbc, 0xb6, 0xf4, 0x5c, 0xe1, 0xa2, 0x42, 0x04, 0xab, 0x5d, 0x36, 0xee, 0xe8,
	0x89, 0xa0, 0x18, 0x0e, 0xf7, 0xe0, 0x63, 0x63, 0x38, 0x74, 0x57, 0x0b, 0x41, 0xd8, 0x4f, 0x2b,
	0xc6, 0x05, 0x7a, 0x01, 0x40, 0x03, 0x8b, 0x33, 0x1d, 0xe9, 0x5a, 0x55, 0x7b, 0x94, 0x7f, 0x56,
	0xae, 0xc5, 0xd3, 0xd5, 0x54, 0x44, 0x7f, 0x44, 0x0e, 0x69, 0xf8, 0x88, 0x9b, 0x70, 0x2b, 0xca,
	0xc4, 0x97, 0xee, 0x82, 0x33, 0x54, 0x87, 0x1b, 0xca, 0xaf, 0xf2, 0xdc, 0x4e, 0xcd, 0x43, 0x42,
	0x14, 0x5e, 0xc3, 0x27, 0xca, 0xd6, 0xa6, 0x82, 0x76, 0xa6, 0x33, 0xc1, 0xbc, 0x0f, 0x6d, 0x08,
	0x3d, 0x01, 0x14, 0xc6, 0x8d, 0xa8, 0xa0, 0xce, 0x78, 0x46, 0x2f, 0xb8, 0x9e, 0xa9, 0x6a, 0x8f,
	0x6e, 0x92, 0x22, 0x8d, 0x95, 0xf1, 0xed, 0xd8, 0x02, 0x3d, 0x56, 0xda, 0x12, 0x1e, 0xa3, 0xf3,
	0x90, 0x92, 0xaf, 0x20, 0x37, 0x96, 0xbd, 0xa8, 0xea, 0xf7, 0x53, 0xab, 0x5f, 0xb5, 0x4c, 0x14,
	0x1c, 0x7f, 0x03, 0x95, 0x94, 0xa4, 0x8a, 0x9d, 0xa7, 0x90, 0xf5, 0xfb, 0x52, 0x39, 0x2b, 0xd7,
	0xe6, 0x24, 0x12, 0x86, 0x7f, 0xd7, 0xa0, 0x1c, 0xb3, 0xbe, 0x59, 0x31, 0x6f, 0xfd, 0x5f, 0x1b,
	0x44, 0xf7, 0x21, 0x3f, 0xa7, 0xef, 0x1c, 0x8f, 0xf1, 0xd5, 0x4c, 0x84, 0xe4, 0xc0, 0x9c, 0xbe,
	0x23, 0x81, 0x05, 0x95, 0x20, 0xe7, 0x8e, 0xc7, 0x9c, 0x09, 0x7d, 0x5f, 0xfa, 0xd4, 0x2f, 0xfc,
	0xa7, 0x06, 0xf9, 0x58, 0x5a, 0x54, 0x83, 0x9c, 0xc7, 0x7e, 0xa6, 0x5e, 0xb8, 0xa0, 0xcf, 0x92,
	0x1d, 0x10, 0xe9, 0xeb, 0xed, 0x11, 0x85, 0x42, 0x2f, 0xe1, 0x86, 0xc7, 0x86, 0x6c, 0xba, 0x14,
	0xb2, 0x68, 0xfe, 0x59, 0x35, 0x19, 0x60, 0x7b, 0x74, 0xc1, 0xe9, 0x50, 0x4c, 0xdd, 0x05, 0x09,
	0x70, 0xbd, 0x3d, 0x12, 0x86, 0xa0, 0xc6, 0x95, 0xb0, 0xf6, 0x77, 0x08, 0xcb, 0x0f, 0x51, 0xb8,
	0x66, 0x0e, 0xb2, 0x53, 0xc1, 0xe6, 0xf8, 0x97, 0xc4, 0x9e, 0x15, 0x8b, 0x6a, 0x23, 0x0f, 0xe0,
	0xa6, 0x70, 0x05, 0x9d, 0x45, 0x7c, 0x68, 0x72, 0xe6, 0x82, 0x34, 0x86, 0x8c, 0xbc, 0x84, 0x42,
	0x24, 0x47, 0xc1, 0xe6, 0x7a, 0xa6, 0xba, 0xbf, 0x7b, 0x7d, 0xf9, 0x50, 0x92, 0x7e, 0x79, 0x13,
	0xee, 0x58, 0x3e, 0x88, 0x79, 0x01, 0x25, 0x49, 0xa1, 0x9d, 0x40, 0xe6, 0x3a, 0x89, 0xab, 0xa8,
	0xfe, 0x88, 0x64, 0xa6, 0x23, 0xfc, 0x2d, 0xdc, 0x4d, 0x4d, 0xa3, 0x06, 0x79, 0xf2, 0x3e, 0xdb,
	0x08, 0x77, 0x81, 0x7f, 0xd3, 0xa0, 0xac, 0xb2, 0x6d, 0x29, 0xeb, 0x05, 0x00, 0x0f, 0x5c, 0xce,
	0x3f, 0x77, 0x76, 0xc8, 0xc3, 0xc7, 0x0f, 0x17, 0x96, 0x0b, 0xfa, 0x76, 0x2f, 0xff, 0x66, 0x3f,
	0x35, 0x5f, 0x59, 0xfe, 0x5c, 0x5c, 0xad, 0x26, 0x7d, 0xf8, 0x10, 0x84, 0xdf, 0xc0, 0xad, 0xae,
	0xbc, 0xa2, 0x96, 0x7f, 0x44, 0x7b, 0x94, 0x4f, 0xd0, 0x5d, 0x38, 0xf4, 0x5c, 0x57, 0x38, 0x13,
	0xca, 0x27, 0xb2, 0x46, 0x81, 0x1c, 0xf8, 0x06, 0xe9, 0x3c, 0x86, 0xc2, 0x8c, 0xae, 0x99, 0xe7,
	0x2c, 0x56, 0xf3, 0x73, 0xe6, 0xc9, 0xd1, 0xb2, 0x24, 0x2f, 0x6d, 0x03, 0x69, 0xc2, 0x3a, 0x94,
	0x36, 0x52, 0x2a, 0x3a, 0xb1, 0x0d, 0xe5, 0x2d, 0x8f, 0x1a, 0xee, 0x6b, 0x38, 0xf0, 0xd4, 0xb3,
	0xe2, 0xf9, 0x28, 0xd9, 0xf8, 0x66, 0x60, 0x04, 0xc7, 0x3f, 0x80, 0x1e, 0x73, 0x26, 0x25, 0xf5,
	0x0a, 0xee, 0x25, 0x3e, 0x12, 0xf2, 0x14, 0xfa, 0xc2, 0x55, 0xf7, 0x30, 0xa0, 0x50, 0xbf, 0xb8,
	0x8a, 0xf7, 0x79, 0xf7, 0xb5, 0x1a, 0xdc, 0xc5, 0x5f, 0x33, 0xf0, 0x69, 0x77, 0xdb, 0xf9, 0xbf,
	0x7f, 0xe1, 0x51, 0x13, 0x0a, 0xf1, 0xc1, 0xf5, 0xec, 0x7b, 0x70, 0xda, 0xdb, 0x23, 0xf9, 0x18,
	0x13, 0xfe, 0xd1, 0x90, 0xb7, 0xf7, 0x47, 0xa8, 0xa4, 0x10, 0xac, 0x16, 0xf7, 0x0a, 0x0e, 0x23,
	0x52, 0x75, 0x4d, 0x4a, 0xee, 0xf8, 0xda, 0x2a, 0x21, 0x7f, 0xe4, 0x60, 0xa4, 0x9e, 0x70, 0x19,
	0x6e, 0x1b, 0xcb, 0xa5, 0x79, 0xc9, 0x16, 0x22, 0xb1, 0x3a, 0xdc, 0x81, 0xd2, 0xa6, 0x23, 0x7a,
	0xbf, 0x3f, 0x62, 0xbe, 0x59, 0x71, 0x5f, 0xda, 0x20, 0x43, 0x05, 0x91, 0x00, 0xf4, 0xf8, 0x0f,
	0x2d, 0xfa, 0x34, 0x87, 0xdf, 0x3b, 0x74, 0x0c, 0x47, 0x46, 0xab, 0x75, 0xf6, 0x76, 0x60, 0x3b,
	0x6d, 0xc3, 0x36, 0x9c, 0xce, 0xa9, 0xd1, 0x75, 0xde, 0x0e, 0xac, 0xd7, 0x66, 0xab, 0xdf, 0xe9,
	0x9b, 0xed, 0xe2, 0x1e, 0xfa, 0x02, 0x1e, 0x6e, 0x43, 0x6c, 0x62, 0x0c, 0x2c, 0xa3, 0x65, 0xf7,
	0xcf, 0x06, 0x0e, 0x31, 0x5b, 0x66, 0xff, 0xb5, 0x5d, 0xd4, 0xd0, 0x3d, 0xd0, 0xb7, 0xa1, 0xc4,
	0xfc, 0xde, 0x20, 0xed, 0x62, 0x06, 0x1d, 0x41, 0x65, 0xdb, 0xab, 0x2c, 0xc5, 0xec, 0xe3, 0xbf,
	0xb4, 0xc4, 0x4b, 0x11, 0x97, 0x1f, 0xfa, 0x12, 0x4e, 0xba, 0xa7, 0x67, 0x4d, 0xe3, 0xd4, 0xb1,
	0x6c, 0xc3, 0x36, 0x83, 0xf8, 0xbe, 0x6d, 0x7e, 0x97, 0xd6, 0xf0, 0x73, 0xa8, 0xef, 0x02, 0xa7,
	0xb7, 0xfe, 0x39, 0xe0, 0x5d, 0x41, 0xd1, 0x10, 0x27, 0xf0, 0x60, 0x17, 0x2e, 0x1a, 0x07, 0x35,
	0xe0, 0xe9, 0x2e, 0x60, 0xc2, 0xd7, 0x33, 0xac, 0x5e, 0xf1, 0xe0, 0x3c, 0x27, 0xff, 0x8b, 0x3d,
	0xff, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xf3, 0xec, 0xb5, 0x35, 0xdc, 0x09, 0x00, 0x00,
}
