// Code generated by protoc-gen-go. DO NOT EDIT.
// source: spacemesh/v1/mesh.proto

package spacemesh_v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("spacemesh/v1/mesh.proto", fileDescriptor_c9578d5a316dda8b) }

var fileDescriptor_c9578d5a316dda8b = []byte{
	// 345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xcf, 0x4f, 0xc2, 0x30,
	0x14, 0xc7, 0xe3, 0x41, 0x0e, 0x85, 0x78, 0x68, 0xfc, 0x95, 0x11, 0x13, 0x31, 0x5e, 0xd4, 0xa4,
	0x13, 0xbd, 0x7a, 0x31, 0x4a, 0x54, 0x22, 0x44, 0x81, 0xbb, 0x29, 0xf5, 0x09, 0x4b, 0x5c, 0x3b,
	0xfb, 0x3a, 0xe2, 0xfe, 0x5f, 0xff, 0x10, 0x43, 0x3b, 0xe6, 0xaa, 0x8c, 0xe0, 0x69, 0x87, 0xf7,
	0xfd, 0x7c, 0xbe, 0xef, 0x65, 0x29, 0xd9, 0xc3, 0x84, 0x0b, 0x88, 0x01, 0xa7, 0xe1, 0xac, 0x1d,
	0xce, 0xbf, 0x2c, 0xd1, 0xca, 0x28, 0xda, 0x28, 0x06, 0x6c, 0xd6, 0x0e, 0x9a, 0x13, 0xa5, 0x26,
	0xef, 0x10, 0xda, 0xd9, 0x38, 0x7d, 0x0b, 0x21, 0x4e, 0x4c, 0xe6, 0xa2, 0xc1, 0xc1, 0x1f, 0xc7,
	0x8b, 0xc9, 0x12, 0x40, 0x37, 0xbe, 0xf8, 0xaa, 0x91, 0x7a, 0x0f, 0x70, 0x3a, 0x04, 0x3d, 0x8b,
	0x04, 0xd0, 0x7b, 0x52, 0xbf, 0x03, 0x09, 0x18, 0xe1, 0x28, 0x8a, 0x81, 0xee, 0x32, 0xe7, 0x66,
	0x0b, 0x37, 0xeb, 0xcc, 0xdd, 0x41, 0x8b, 0x95, 0x37, 0x60, 0x25, 0x64, 0x00, 0x98, 0x28, 0x89,
	0x40, 0xbb, 0xa4, 0x71, 0x93, 0x6a, 0x0d, 0xd2, 0x3c, 0xf2, 0x0c, 0x74, 0xa5, 0xea, 0xc8, 0x57,
	0x95, 0x99, 0x25, 0xae, 0x4e, 0xa2, 0xc4, 0xf4, 0x9f, 0x2e, 0xcb, 0x14, 0xae, 0x2b, 0xb2, 0xd9,
	0x07, 0xf3, 0xf0, 0x5a, 0x29, 0x69, 0xfa, 0x12, 0x1b, 0x2e, 0xe8, 0x3e, 0xd9, 0xb2, 0xba, 0x7e,
	0x1a, 0xdb, 0x15, 0xb1, 0x52, 0x73, 0xec, 0x6b, 0x7c, 0xaa, 0xf0, 0x8d, 0xc9, 0x7e, 0x8f, 0x7f,
	0x8e, 0x34, 0x97, 0xc8, 0x85, 0x89, 0x94, 0xc4, 0x27, 0xd0, 0x43, 0x10, 0x4a, 0x56, 0x2f, 0xc8,
	0x7c, 0x73, 0x15, 0x5f, 0x74, 0xc4, 0x64, 0xfb, 0x5a, 0x08, 0x95, 0x4a, 0x33, 0xff, 0xd3, 0xb7,
	0xdc, 0xf0, 0xe7, 0x14, 0x74, 0x46, 0x4f, 0x7c, 0xcf, 0xb2, 0xcc, 0x00, 0x3e, 0x52, 0x40, 0x13,
	0x9c, 0xae, 0x13, 0xcd, 0xeb, 0x06, 0xa4, 0xee, 0x8e, 0x74, 0x2d, 0x87, 0x3e, 0x5a, 0x1a, 0x2d,
	0xe4, 0xad, 0x15, 0x89, 0xdc, 0xa9, 0xc9, 0xce, 0xaf, 0xce, 0xa1, 0xd1, 0xc0, 0x63, 0xba, 0x7a,
	0x31, 0x17, 0x5a, 0xf4, 0x9c, 0xad, 0x95, 0x75, 0x8d, 0xe7, 0x1b, 0xb4, 0x9b, 0xdf, 0x91, 0x37,
	0xad, 0xf9, 0x14, 0x4a, 0xc8, 0x8f, 0x6b, 0x5c, 0xb3, 0xd0, 0xe5, 0x77, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xe0, 0x81, 0xc0, 0x88, 0xd2, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MeshServiceClient is the client API for MeshService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MeshServiceClient interface {
	// Network genesis time as unix epoch time
	GenesisTime(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GenesisTimeResponse, error)
	// Current layer number
	CurrentLayer(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*CurrentLayerResponse, error)
	// Current epoch number
	CurrentEpoch(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*CurrentEpochResponse, error)
	// Network ID
	NetId(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*NetIdResponse, error)
	// Number of layers per epoch (a network parameter)
	EpochNumLayers(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*EpochNumLayersResponse, error)
	// Number of transactions per second (a network parameter)
	MaxTransactionsPerSecond(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*MaxTransactionsPerSecondResponse, error)
	// Get account data query
	AccountMeshDataQuery(ctx context.Context, in *AccountMeshDataQueryRequest, opts ...grpc.CallOption) (*AccountMeshDataQueryResponse, error)
	// Layers data query
	LayersQuery(ctx context.Context, in *LayersQueryRequest, opts ...grpc.CallOption) (*LayersQueryResponse, error)
	// A stream of transactions and activations from an account.
	// Includes simple coin transactions with the account as the destination.
	AccountMeshDataStream(ctx context.Context, in *AccountMeshDataStreamRequest, opts ...grpc.CallOption) (MeshService_AccountMeshDataStreamClient, error)
	// Layer with blocks, transactions and activations
	// Sent each time layer data changes. Designed for heavy-duty clients.
	LayerStream(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (MeshService_LayerStreamClient, error)
}

type meshServiceClient struct {
	cc *grpc.ClientConn
}

func NewMeshServiceClient(cc *grpc.ClientConn) MeshServiceClient {
	return &meshServiceClient{cc}
}

func (c *meshServiceClient) GenesisTime(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GenesisTimeResponse, error) {
	out := new(GenesisTimeResponse)
	err := c.cc.Invoke(ctx, "/spacemesh.v1.MeshService/GenesisTime", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshServiceClient) CurrentLayer(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*CurrentLayerResponse, error) {
	out := new(CurrentLayerResponse)
	err := c.cc.Invoke(ctx, "/spacemesh.v1.MeshService/CurrentLayer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshServiceClient) CurrentEpoch(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*CurrentEpochResponse, error) {
	out := new(CurrentEpochResponse)
	err := c.cc.Invoke(ctx, "/spacemesh.v1.MeshService/CurrentEpoch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshServiceClient) NetId(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*NetIdResponse, error) {
	out := new(NetIdResponse)
	err := c.cc.Invoke(ctx, "/spacemesh.v1.MeshService/NetId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshServiceClient) EpochNumLayers(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*EpochNumLayersResponse, error) {
	out := new(EpochNumLayersResponse)
	err := c.cc.Invoke(ctx, "/spacemesh.v1.MeshService/EpochNumLayers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshServiceClient) MaxTransactionsPerSecond(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*MaxTransactionsPerSecondResponse, error) {
	out := new(MaxTransactionsPerSecondResponse)
	err := c.cc.Invoke(ctx, "/spacemesh.v1.MeshService/MaxTransactionsPerSecond", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshServiceClient) AccountMeshDataQuery(ctx context.Context, in *AccountMeshDataQueryRequest, opts ...grpc.CallOption) (*AccountMeshDataQueryResponse, error) {
	out := new(AccountMeshDataQueryResponse)
	err := c.cc.Invoke(ctx, "/spacemesh.v1.MeshService/AccountMeshDataQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshServiceClient) LayersQuery(ctx context.Context, in *LayersQueryRequest, opts ...grpc.CallOption) (*LayersQueryResponse, error) {
	out := new(LayersQueryResponse)
	err := c.cc.Invoke(ctx, "/spacemesh.v1.MeshService/LayersQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshServiceClient) AccountMeshDataStream(ctx context.Context, in *AccountMeshDataStreamRequest, opts ...grpc.CallOption) (MeshService_AccountMeshDataStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MeshService_serviceDesc.Streams[0], "/spacemesh.v1.MeshService/AccountMeshDataStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &meshServiceAccountMeshDataStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MeshService_AccountMeshDataStreamClient interface {
	Recv() (*AccountMeshDataStreamResponse, error)
	grpc.ClientStream
}

type meshServiceAccountMeshDataStreamClient struct {
	grpc.ClientStream
}

func (x *meshServiceAccountMeshDataStreamClient) Recv() (*AccountMeshDataStreamResponse, error) {
	m := new(AccountMeshDataStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *meshServiceClient) LayerStream(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (MeshService_LayerStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MeshService_serviceDesc.Streams[1], "/spacemesh.v1.MeshService/LayerStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &meshServiceLayerStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MeshService_LayerStreamClient interface {
	Recv() (*LayerStreamResponse, error)
	grpc.ClientStream
}

type meshServiceLayerStreamClient struct {
	grpc.ClientStream
}

func (x *meshServiceLayerStreamClient) Recv() (*LayerStreamResponse, error) {
	m := new(LayerStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MeshServiceServer is the server API for MeshService service.
type MeshServiceServer interface {
	// Network genesis time as unix epoch time
	GenesisTime(context.Context, *empty.Empty) (*GenesisTimeResponse, error)
	// Current layer number
	CurrentLayer(context.Context, *empty.Empty) (*CurrentLayerResponse, error)
	// Current epoch number
	CurrentEpoch(context.Context, *empty.Empty) (*CurrentEpochResponse, error)
	// Network ID
	NetId(context.Context, *empty.Empty) (*NetIdResponse, error)
	// Number of layers per epoch (a network parameter)
	EpochNumLayers(context.Context, *empty.Empty) (*EpochNumLayersResponse, error)
	// Number of transactions per second (a network parameter)
	MaxTransactionsPerSecond(context.Context, *empty.Empty) (*MaxTransactionsPerSecondResponse, error)
	// Get account data query
	AccountMeshDataQuery(context.Context, *AccountMeshDataQueryRequest) (*AccountMeshDataQueryResponse, error)
	// Layers data query
	LayersQuery(context.Context, *LayersQueryRequest) (*LayersQueryResponse, error)
	// A stream of transactions and activations from an account.
	// Includes simple coin transactions with the account as the destination.
	AccountMeshDataStream(*AccountMeshDataStreamRequest, MeshService_AccountMeshDataStreamServer) error
	// Layer with blocks, transactions and activations
	// Sent each time layer data changes. Designed for heavy-duty clients.
	LayerStream(*empty.Empty, MeshService_LayerStreamServer) error
}

// UnimplementedMeshServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMeshServiceServer struct {
}

func (*UnimplementedMeshServiceServer) GenesisTime(ctx context.Context, req *empty.Empty) (*GenesisTimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenesisTime not implemented")
}
func (*UnimplementedMeshServiceServer) CurrentLayer(ctx context.Context, req *empty.Empty) (*CurrentLayerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CurrentLayer not implemented")
}
func (*UnimplementedMeshServiceServer) CurrentEpoch(ctx context.Context, req *empty.Empty) (*CurrentEpochResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CurrentEpoch not implemented")
}
func (*UnimplementedMeshServiceServer) NetId(ctx context.Context, req *empty.Empty) (*NetIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NetId not implemented")
}
func (*UnimplementedMeshServiceServer) EpochNumLayers(ctx context.Context, req *empty.Empty) (*EpochNumLayersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EpochNumLayers not implemented")
}
func (*UnimplementedMeshServiceServer) MaxTransactionsPerSecond(ctx context.Context, req *empty.Empty) (*MaxTransactionsPerSecondResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MaxTransactionsPerSecond not implemented")
}
func (*UnimplementedMeshServiceServer) AccountMeshDataQuery(ctx context.Context, req *AccountMeshDataQueryRequest) (*AccountMeshDataQueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccountMeshDataQuery not implemented")
}
func (*UnimplementedMeshServiceServer) LayersQuery(ctx context.Context, req *LayersQueryRequest) (*LayersQueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LayersQuery not implemented")
}
func (*UnimplementedMeshServiceServer) AccountMeshDataStream(req *AccountMeshDataStreamRequest, srv MeshService_AccountMeshDataStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method AccountMeshDataStream not implemented")
}
func (*UnimplementedMeshServiceServer) LayerStream(req *empty.Empty, srv MeshService_LayerStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method LayerStream not implemented")
}

func RegisterMeshServiceServer(s *grpc.Server, srv MeshServiceServer) {
	s.RegisterService(&_MeshService_serviceDesc, srv)
}

func _MeshService_GenesisTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServiceServer).GenesisTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spacemesh.v1.MeshService/GenesisTime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServiceServer).GenesisTime(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshService_CurrentLayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServiceServer).CurrentLayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spacemesh.v1.MeshService/CurrentLayer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServiceServer).CurrentLayer(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshService_CurrentEpoch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServiceServer).CurrentEpoch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spacemesh.v1.MeshService/CurrentEpoch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServiceServer).CurrentEpoch(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshService_NetId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServiceServer).NetId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spacemesh.v1.MeshService/NetId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServiceServer).NetId(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshService_EpochNumLayers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServiceServer).EpochNumLayers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spacemesh.v1.MeshService/EpochNumLayers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServiceServer).EpochNumLayers(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshService_MaxTransactionsPerSecond_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServiceServer).MaxTransactionsPerSecond(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spacemesh.v1.MeshService/MaxTransactionsPerSecond",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServiceServer).MaxTransactionsPerSecond(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshService_AccountMeshDataQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountMeshDataQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServiceServer).AccountMeshDataQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spacemesh.v1.MeshService/AccountMeshDataQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServiceServer).AccountMeshDataQuery(ctx, req.(*AccountMeshDataQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshService_LayersQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LayersQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServiceServer).LayersQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spacemesh.v1.MeshService/LayersQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServiceServer).LayersQuery(ctx, req.(*LayersQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshService_AccountMeshDataStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AccountMeshDataStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MeshServiceServer).AccountMeshDataStream(m, &meshServiceAccountMeshDataStreamServer{stream})
}

type MeshService_AccountMeshDataStreamServer interface {
	Send(*AccountMeshDataStreamResponse) error
	grpc.ServerStream
}

type meshServiceAccountMeshDataStreamServer struct {
	grpc.ServerStream
}

func (x *meshServiceAccountMeshDataStreamServer) Send(m *AccountMeshDataStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _MeshService_LayerStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MeshServiceServer).LayerStream(m, &meshServiceLayerStreamServer{stream})
}

type MeshService_LayerStreamServer interface {
	Send(*LayerStreamResponse) error
	grpc.ServerStream
}

type meshServiceLayerStreamServer struct {
	grpc.ServerStream
}

func (x *meshServiceLayerStreamServer) Send(m *LayerStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _MeshService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "spacemesh.v1.MeshService",
	HandlerType: (*MeshServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenesisTime",
			Handler:    _MeshService_GenesisTime_Handler,
		},
		{
			MethodName: "CurrentLayer",
			Handler:    _MeshService_CurrentLayer_Handler,
		},
		{
			MethodName: "CurrentEpoch",
			Handler:    _MeshService_CurrentEpoch_Handler,
		},
		{
			MethodName: "NetId",
			Handler:    _MeshService_NetId_Handler,
		},
		{
			MethodName: "EpochNumLayers",
			Handler:    _MeshService_EpochNumLayers_Handler,
		},
		{
			MethodName: "MaxTransactionsPerSecond",
			Handler:    _MeshService_MaxTransactionsPerSecond_Handler,
		},
		{
			MethodName: "AccountMeshDataQuery",
			Handler:    _MeshService_AccountMeshDataQuery_Handler,
		},
		{
			MethodName: "LayersQuery",
			Handler:    _MeshService_LayersQuery_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AccountMeshDataStream",
			Handler:       _MeshService_AccountMeshDataStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "LayerStream",
			Handler:       _MeshService_LayerStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "spacemesh/v1/mesh.proto",
}
