// Code generated by protoc-gen-go. DO NOT EDIT.
// source: spacemesh/v1/mesh_types.proto

package spacemesh_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AccountMeshDataFlag int32

const (
	AccountMeshDataFlag_ACCOUNT_MESH_DATA_FLAG_UNSPECIFIED  AccountMeshDataFlag = 0
	AccountMeshDataFlag_ACCOUNT_MESH_DATA_FLAG_TRANSACTIONS AccountMeshDataFlag = 1
	AccountMeshDataFlag_ACCOUNT_MESH_DATA_FLAG_ACTIVATIONS  AccountMeshDataFlag = 2
)

var AccountMeshDataFlag_name = map[int32]string{
	0: "ACCOUNT_MESH_DATA_FLAG_UNSPECIFIED",
	1: "ACCOUNT_MESH_DATA_FLAG_TRANSACTIONS",
	2: "ACCOUNT_MESH_DATA_FLAG_ACTIVATIONS",
}

var AccountMeshDataFlag_value = map[string]int32{
	"ACCOUNT_MESH_DATA_FLAG_UNSPECIFIED":  0,
	"ACCOUNT_MESH_DATA_FLAG_TRANSACTIONS": 1,
	"ACCOUNT_MESH_DATA_FLAG_ACTIVATIONS":  2,
}

func (x AccountMeshDataFlag) String() string {
	return proto.EnumName(AccountMeshDataFlag_name, int32(x))
}

func (AccountMeshDataFlag) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_44b46d8841336308, []int{0}
}

type GenesisTimeResponse struct {
	Unixtime             *SimpleInt `protobuf:"bytes,1,opt,name=unixtime,proto3" json:"unixtime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GenesisTimeResponse) Reset()         { *m = GenesisTimeResponse{} }
func (m *GenesisTimeResponse) String() string { return proto.CompactTextString(m) }
func (*GenesisTimeResponse) ProtoMessage()    {}
func (*GenesisTimeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_44b46d8841336308, []int{0}
}

func (m *GenesisTimeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenesisTimeResponse.Unmarshal(m, b)
}
func (m *GenesisTimeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenesisTimeResponse.Marshal(b, m, deterministic)
}
func (m *GenesisTimeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisTimeResponse.Merge(m, src)
}
func (m *GenesisTimeResponse) XXX_Size() int {
	return xxx_messageInfo_GenesisTimeResponse.Size(m)
}
func (m *GenesisTimeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisTimeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisTimeResponse proto.InternalMessageInfo

func (m *GenesisTimeResponse) GetUnixtime() *SimpleInt {
	if m != nil {
		return m.Unixtime
	}
	return nil
}

type CurrentLayerResponse struct {
	Layernum             *SimpleInt `protobuf:"bytes,1,opt,name=layernum,proto3" json:"layernum,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CurrentLayerResponse) Reset()         { *m = CurrentLayerResponse{} }
func (m *CurrentLayerResponse) String() string { return proto.CompactTextString(m) }
func (*CurrentLayerResponse) ProtoMessage()    {}
func (*CurrentLayerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_44b46d8841336308, []int{1}
}

func (m *CurrentLayerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CurrentLayerResponse.Unmarshal(m, b)
}
func (m *CurrentLayerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CurrentLayerResponse.Marshal(b, m, deterministic)
}
func (m *CurrentLayerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrentLayerResponse.Merge(m, src)
}
func (m *CurrentLayerResponse) XXX_Size() int {
	return xxx_messageInfo_CurrentLayerResponse.Size(m)
}
func (m *CurrentLayerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrentLayerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CurrentLayerResponse proto.InternalMessageInfo

func (m *CurrentLayerResponse) GetLayernum() *SimpleInt {
	if m != nil {
		return m.Layernum
	}
	return nil
}

type CurrentEpochResponse struct {
	Epochnum             *SimpleInt `protobuf:"bytes,1,opt,name=epochnum,proto3" json:"epochnum,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CurrentEpochResponse) Reset()         { *m = CurrentEpochResponse{} }
func (m *CurrentEpochResponse) String() string { return proto.CompactTextString(m) }
func (*CurrentEpochResponse) ProtoMessage()    {}
func (*CurrentEpochResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_44b46d8841336308, []int{2}
}

func (m *CurrentEpochResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CurrentEpochResponse.Unmarshal(m, b)
}
func (m *CurrentEpochResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CurrentEpochResponse.Marshal(b, m, deterministic)
}
func (m *CurrentEpochResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrentEpochResponse.Merge(m, src)
}
func (m *CurrentEpochResponse) XXX_Size() int {
	return xxx_messageInfo_CurrentEpochResponse.Size(m)
}
func (m *CurrentEpochResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrentEpochResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CurrentEpochResponse proto.InternalMessageInfo

func (m *CurrentEpochResponse) GetEpochnum() *SimpleInt {
	if m != nil {
		return m.Epochnum
	}
	return nil
}

type NetIdResponse struct {
	Netid                *SimpleInt `protobuf:"bytes,1,opt,name=netid,proto3" json:"netid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *NetIdResponse) Reset()         { *m = NetIdResponse{} }
func (m *NetIdResponse) String() string { return proto.CompactTextString(m) }
func (*NetIdResponse) ProtoMessage()    {}
func (*NetIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_44b46d8841336308, []int{3}
}

func (m *NetIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetIdResponse.Unmarshal(m, b)
}
func (m *NetIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetIdResponse.Marshal(b, m, deterministic)
}
func (m *NetIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetIdResponse.Merge(m, src)
}
func (m *NetIdResponse) XXX_Size() int {
	return xxx_messageInfo_NetIdResponse.Size(m)
}
func (m *NetIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NetIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NetIdResponse proto.InternalMessageInfo

func (m *NetIdResponse) GetNetid() *SimpleInt {
	if m != nil {
		return m.Netid
	}
	return nil
}

type EpochNumLayersResponse struct {
	Numlayers            *SimpleInt `protobuf:"bytes,1,opt,name=numlayers,proto3" json:"numlayers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *EpochNumLayersResponse) Reset()         { *m = EpochNumLayersResponse{} }
func (m *EpochNumLayersResponse) String() string { return proto.CompactTextString(m) }
func (*EpochNumLayersResponse) ProtoMessage()    {}
func (*EpochNumLayersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_44b46d8841336308, []int{4}
}

func (m *EpochNumLayersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EpochNumLayersResponse.Unmarshal(m, b)
}
func (m *EpochNumLayersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EpochNumLayersResponse.Marshal(b, m, deterministic)
}
func (m *EpochNumLayersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EpochNumLayersResponse.Merge(m, src)
}
func (m *EpochNumLayersResponse) XXX_Size() int {
	return xxx_messageInfo_EpochNumLayersResponse.Size(m)
}
func (m *EpochNumLayersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EpochNumLayersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EpochNumLayersResponse proto.InternalMessageInfo

func (m *EpochNumLayersResponse) GetNumlayers() *SimpleInt {
	if m != nil {
		return m.Numlayers
	}
	return nil
}

type MaxTransactionsPerSecondResponse struct {
	Maxtxpersecond       *SimpleInt `protobuf:"bytes,1,opt,name=maxtxpersecond,proto3" json:"maxtxpersecond,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MaxTransactionsPerSecondResponse) Reset()         { *m = MaxTransactionsPerSecondResponse{} }
func (m *MaxTransactionsPerSecondResponse) String() string { return proto.CompactTextString(m) }
func (*MaxTransactionsPerSecondResponse) ProtoMessage()    {}
func (*MaxTransactionsPerSecondResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_44b46d8841336308, []int{5}
}

func (m *MaxTransactionsPerSecondResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MaxTransactionsPerSecondResponse.Unmarshal(m, b)
}
func (m *MaxTransactionsPerSecondResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MaxTransactionsPerSecondResponse.Marshal(b, m, deterministic)
}
func (m *MaxTransactionsPerSecondResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MaxTransactionsPerSecondResponse.Merge(m, src)
}
func (m *MaxTransactionsPerSecondResponse) XXX_Size() int {
	return xxx_messageInfo_MaxTransactionsPerSecondResponse.Size(m)
}
func (m *MaxTransactionsPerSecondResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MaxTransactionsPerSecondResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MaxTransactionsPerSecondResponse proto.InternalMessageInfo

func (m *MaxTransactionsPerSecondResponse) GetMaxtxpersecond() *SimpleInt {
	if m != nil {
		return m.Maxtxpersecond
	}
	return nil
}

type AccountMeshDataFilter struct {
	AccountId            *AccountId `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AccountMeshDataFlags uint32     `protobuf:"varint,2,opt,name=account_mesh_data_flags,json=accountMeshDataFlags,proto3" json:"account_mesh_data_flags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AccountMeshDataFilter) Reset()         { *m = AccountMeshDataFilter{} }
func (m *AccountMeshDataFilter) String() string { return proto.CompactTextString(m) }
func (*AccountMeshDataFilter) ProtoMessage()    {}
func (*AccountMeshDataFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_44b46d8841336308, []int{6}
}

func (m *AccountMeshDataFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountMeshDataFilter.Unmarshal(m, b)
}
func (m *AccountMeshDataFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountMeshDataFilter.Marshal(b, m, deterministic)
}
func (m *AccountMeshDataFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountMeshDataFilter.Merge(m, src)
}
func (m *AccountMeshDataFilter) XXX_Size() int {
	return xxx_messageInfo_AccountMeshDataFilter.Size(m)
}
func (m *AccountMeshDataFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountMeshDataFilter.DiscardUnknown(m)
}

var xxx_messageInfo_AccountMeshDataFilter proto.InternalMessageInfo

func (m *AccountMeshDataFilter) GetAccountId() *AccountId {
	if m != nil {
		return m.AccountId
	}
	return nil
}

func (m *AccountMeshDataFilter) GetAccountMeshDataFlags() uint32 {
	if m != nil {
		return m.AccountMeshDataFlags
	}
	return 0
}

type AccountMeshData struct {
	// Types that are valid to be assigned to DataItem:
	//	*AccountMeshData_Transaction
	//	*AccountMeshData_Activation
	DataItem             isAccountMeshData_DataItem `protobuf_oneof:"data_item"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *AccountMeshData) Reset()         { *m = AccountMeshData{} }
func (m *AccountMeshData) String() string { return proto.CompactTextString(m) }
func (*AccountMeshData) ProtoMessage()    {}
func (*AccountMeshData) Descriptor() ([]byte, []int) {
	return fileDescriptor_44b46d8841336308, []int{7}
}

func (m *AccountMeshData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountMeshData.Unmarshal(m, b)
}
func (m *AccountMeshData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountMeshData.Marshal(b, m, deterministic)
}
func (m *AccountMeshData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountMeshData.Merge(m, src)
}
func (m *AccountMeshData) XXX_Size() int {
	return xxx_messageInfo_AccountMeshData.Size(m)
}
func (m *AccountMeshData) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountMeshData.DiscardUnknown(m)
}

var xxx_messageInfo_AccountMeshData proto.InternalMessageInfo

type isAccountMeshData_DataItem interface {
	isAccountMeshData_DataItem()
}

type AccountMeshData_Transaction struct {
	Transaction *Transaction `protobuf:"bytes,1,opt,name=transaction,proto3,oneof"`
}

type AccountMeshData_Activation struct {
	Activation *Activation `protobuf:"bytes,2,opt,name=activation,proto3,oneof"`
}

func (*AccountMeshData_Transaction) isAccountMeshData_DataItem() {}

func (*AccountMeshData_Activation) isAccountMeshData_DataItem() {}

func (m *AccountMeshData) GetDataItem() isAccountMeshData_DataItem {
	if m != nil {
		return m.DataItem
	}
	return nil
}

func (m *AccountMeshData) GetTransaction() *Transaction {
	if x, ok := m.GetDataItem().(*AccountMeshData_Transaction); ok {
		return x.Transaction
	}
	return nil
}

func (m *AccountMeshData) GetActivation() *Activation {
	if x, ok := m.GetDataItem().(*AccountMeshData_Activation); ok {
		return x.Activation
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*AccountMeshData) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*AccountMeshData_Transaction)(nil),
		(*AccountMeshData_Activation)(nil),
	}
}

type AccountMeshDataStreamRequest struct {
	Filter               *AccountMeshDataFilter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *AccountMeshDataStreamRequest) Reset()         { *m = AccountMeshDataStreamRequest{} }
func (m *AccountMeshDataStreamRequest) String() string { return proto.CompactTextString(m) }
func (*AccountMeshDataStreamRequest) ProtoMessage()    {}
func (*AccountMeshDataStreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_44b46d8841336308, []int{8}
}

func (m *AccountMeshDataStreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountMeshDataStreamRequest.Unmarshal(m, b)
}
func (m *AccountMeshDataStreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountMeshDataStreamRequest.Marshal(b, m, deterministic)
}
func (m *AccountMeshDataStreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountMeshDataStreamRequest.Merge(m, src)
}
func (m *AccountMeshDataStreamRequest) XXX_Size() int {
	return xxx_messageInfo_AccountMeshDataStreamRequest.Size(m)
}
func (m *AccountMeshDataStreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountMeshDataStreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountMeshDataStreamRequest proto.InternalMessageInfo

func (m *AccountMeshDataStreamRequest) GetFilter() *AccountMeshDataFilter {
	if m != nil {
		return m.Filter
	}
	return nil
}

type AccountMeshDataStreamResponse struct {
	Data                 *AccountMeshData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AccountMeshDataStreamResponse) Reset()         { *m = AccountMeshDataStreamResponse{} }
func (m *AccountMeshDataStreamResponse) String() string { return proto.CompactTextString(m) }
func (*AccountMeshDataStreamResponse) ProtoMessage()    {}
func (*AccountMeshDataStreamResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_44b46d8841336308, []int{9}
}

func (m *AccountMeshDataStreamResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountMeshDataStreamResponse.Unmarshal(m, b)
}
func (m *AccountMeshDataStreamResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountMeshDataStreamResponse.Marshal(b, m, deterministic)
}
func (m *AccountMeshDataStreamResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountMeshDataStreamResponse.Merge(m, src)
}
func (m *AccountMeshDataStreamResponse) XXX_Size() int {
	return xxx_messageInfo_AccountMeshDataStreamResponse.Size(m)
}
func (m *AccountMeshDataStreamResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountMeshDataStreamResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AccountMeshDataStreamResponse proto.InternalMessageInfo

func (m *AccountMeshDataStreamResponse) GetData() *AccountMeshData {
	if m != nil {
		return m.Data
	}
	return nil
}

type AccountMeshDataQueryRequest struct {
	Filter               *AccountMeshDataFilter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	MinLayer             uint64                 `protobuf:"varint,2,opt,name=min_layer,json=minLayer,proto3" json:"min_layer,omitempty"`
	MaxResults           uint32                 `protobuf:"varint,3,opt,name=max_results,json=maxResults,proto3" json:"max_results,omitempty"`
	Offset               uint32                 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *AccountMeshDataQueryRequest) Reset()         { *m = AccountMeshDataQueryRequest{} }
func (m *AccountMeshDataQueryRequest) String() string { return proto.CompactTextString(m) }
func (*AccountMeshDataQueryRequest) ProtoMessage()    {}
func (*AccountMeshDataQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_44b46d8841336308, []int{10}
}

func (m *AccountMeshDataQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountMeshDataQueryRequest.Unmarshal(m, b)
}
func (m *AccountMeshDataQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountMeshDataQueryRequest.Marshal(b, m, deterministic)
}
func (m *AccountMeshDataQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountMeshDataQueryRequest.Merge(m, src)
}
func (m *AccountMeshDataQueryRequest) XXX_Size() int {
	return xxx_messageInfo_AccountMeshDataQueryRequest.Size(m)
}
func (m *AccountMeshDataQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountMeshDataQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountMeshDataQueryRequest proto.InternalMessageInfo

func (m *AccountMeshDataQueryRequest) GetFilter() *AccountMeshDataFilter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *AccountMeshDataQueryRequest) GetMinLayer() uint64 {
	if m != nil {
		return m.MinLayer
	}
	return 0
}

func (m *AccountMeshDataQueryRequest) GetMaxResults() uint32 {
	if m != nil {
		return m.MaxResults
	}
	return 0
}

func (m *AccountMeshDataQueryRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type AccountMeshDataQueryResponse struct {
	Data                 []*AccountMeshData `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	TotalResults         uint32             `protobuf:"varint,2,opt,name=total_results,json=totalResults,proto3" json:"total_results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *AccountMeshDataQueryResponse) Reset()         { *m = AccountMeshDataQueryResponse{} }
func (m *AccountMeshDataQueryResponse) String() string { return proto.CompactTextString(m) }
func (*AccountMeshDataQueryResponse) ProtoMessage()    {}
func (*AccountMeshDataQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_44b46d8841336308, []int{11}
}

func (m *AccountMeshDataQueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountMeshDataQueryResponse.Unmarshal(m, b)
}
func (m *AccountMeshDataQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountMeshDataQueryResponse.Marshal(b, m, deterministic)
}
func (m *AccountMeshDataQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountMeshDataQueryResponse.Merge(m, src)
}
func (m *AccountMeshDataQueryResponse) XXX_Size() int {
	return xxx_messageInfo_AccountMeshDataQueryResponse.Size(m)
}
func (m *AccountMeshDataQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountMeshDataQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AccountMeshDataQueryResponse proto.InternalMessageInfo

func (m *AccountMeshDataQueryResponse) GetData() []*AccountMeshData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *AccountMeshDataQueryResponse) GetTotalResults() uint32 {
	if m != nil {
		return m.TotalResults
	}
	return 0
}

type LayersQueryRequest struct {
	StartLayer           uint32   `protobuf:"varint,1,opt,name=start_layer,json=startLayer,proto3" json:"start_layer,omitempty"`
	EndLayer             uint32   `protobuf:"varint,2,opt,name=end_layer,json=endLayer,proto3" json:"end_layer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LayersQueryRequest) Reset()         { *m = LayersQueryRequest{} }
func (m *LayersQueryRequest) String() string { return proto.CompactTextString(m) }
func (*LayersQueryRequest) ProtoMessage()    {}
func (*LayersQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_44b46d8841336308, []int{12}
}

func (m *LayersQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LayersQueryRequest.Unmarshal(m, b)
}
func (m *LayersQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LayersQueryRequest.Marshal(b, m, deterministic)
}
func (m *LayersQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LayersQueryRequest.Merge(m, src)
}
func (m *LayersQueryRequest) XXX_Size() int {
	return xxx_messageInfo_LayersQueryRequest.Size(m)
}
func (m *LayersQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LayersQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LayersQueryRequest proto.InternalMessageInfo

func (m *LayersQueryRequest) GetStartLayer() uint32 {
	if m != nil {
		return m.StartLayer
	}
	return 0
}

func (m *LayersQueryRequest) GetEndLayer() uint32 {
	if m != nil {
		return m.EndLayer
	}
	return 0
}

type LayersQueryResponse struct {
	Layer                []*Layer `protobuf:"bytes,1,rep,name=layer,proto3" json:"layer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LayersQueryResponse) Reset()         { *m = LayersQueryResponse{} }
func (m *LayersQueryResponse) String() string { return proto.CompactTextString(m) }
func (*LayersQueryResponse) ProtoMessage()    {}
func (*LayersQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_44b46d8841336308, []int{13}
}

func (m *LayersQueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LayersQueryResponse.Unmarshal(m, b)
}
func (m *LayersQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LayersQueryResponse.Marshal(b, m, deterministic)
}
func (m *LayersQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LayersQueryResponse.Merge(m, src)
}
func (m *LayersQueryResponse) XXX_Size() int {
	return xxx_messageInfo_LayersQueryResponse.Size(m)
}
func (m *LayersQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LayersQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LayersQueryResponse proto.InternalMessageInfo

func (m *LayersQueryResponse) GetLayer() []*Layer {
	if m != nil {
		return m.Layer
	}
	return nil
}

type LayerStreamResponse struct {
	Layer                *Layer   `protobuf:"bytes,1,opt,name=layer,proto3" json:"layer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LayerStreamResponse) Reset()         { *m = LayerStreamResponse{} }
func (m *LayerStreamResponse) String() string { return proto.CompactTextString(m) }
func (*LayerStreamResponse) ProtoMessage()    {}
func (*LayerStreamResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_44b46d8841336308, []int{14}
}

func (m *LayerStreamResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LayerStreamResponse.Unmarshal(m, b)
}
func (m *LayerStreamResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LayerStreamResponse.Marshal(b, m, deterministic)
}
func (m *LayerStreamResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LayerStreamResponse.Merge(m, src)
}
func (m *LayerStreamResponse) XXX_Size() int {
	return xxx_messageInfo_LayerStreamResponse.Size(m)
}
func (m *LayerStreamResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LayerStreamResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LayerStreamResponse proto.InternalMessageInfo

func (m *LayerStreamResponse) GetLayer() *Layer {
	if m != nil {
		return m.Layer
	}
	return nil
}

func init() {
	proto.RegisterEnum("spacemesh.v1.AccountMeshDataFlag", AccountMeshDataFlag_name, AccountMeshDataFlag_value)
	proto.RegisterType((*GenesisTimeResponse)(nil), "spacemesh.v1.GenesisTimeResponse")
	proto.RegisterType((*CurrentLayerResponse)(nil), "spacemesh.v1.CurrentLayerResponse")
	proto.RegisterType((*CurrentEpochResponse)(nil), "spacemesh.v1.CurrentEpochResponse")
	proto.RegisterType((*NetIdResponse)(nil), "spacemesh.v1.NetIdResponse")
	proto.RegisterType((*EpochNumLayersResponse)(nil), "spacemesh.v1.EpochNumLayersResponse")
	proto.RegisterType((*MaxTransactionsPerSecondResponse)(nil), "spacemesh.v1.MaxTransactionsPerSecondResponse")
	proto.RegisterType((*AccountMeshDataFilter)(nil), "spacemesh.v1.AccountMeshDataFilter")
	proto.RegisterType((*AccountMeshData)(nil), "spacemesh.v1.AccountMeshData")
	proto.RegisterType((*AccountMeshDataStreamRequest)(nil), "spacemesh.v1.AccountMeshDataStreamRequest")
	proto.RegisterType((*AccountMeshDataStreamResponse)(nil), "spacemesh.v1.AccountMeshDataStreamResponse")
	proto.RegisterType((*AccountMeshDataQueryRequest)(nil), "spacemesh.v1.AccountMeshDataQueryRequest")
	proto.RegisterType((*AccountMeshDataQueryResponse)(nil), "spacemesh.v1.AccountMeshDataQueryResponse")
	proto.RegisterType((*LayersQueryRequest)(nil), "spacemesh.v1.LayersQueryRequest")
	proto.RegisterType((*LayersQueryResponse)(nil), "spacemesh.v1.LayersQueryResponse")
	proto.RegisterType((*LayerStreamResponse)(nil), "spacemesh.v1.LayerStreamResponse")
}

func init() { proto.RegisterFile("spacemesh/v1/mesh_types.proto", fileDescriptor_44b46d8841336308) }

var fileDescriptor_44b46d8841336308 = []byte{
	// 679 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0xcf, 0x4e, 0xdb, 0x4a,
	0x18, 0xc5, 0x31, 0xff, 0x44, 0xbe, 0x90, 0x7b, 0xd1, 0x84, 0x0b, 0xb9, 0x97, 0x8b, 0x40, 0x83,
	0xd4, 0xd2, 0x4a, 0x0d, 0xa2, 0x88, 0x2e, 0x5a, 0xf5, 0x8f, 0x1b, 0x02, 0xa4, 0x85, 0x40, 0x27,
	0xa1, 0x9b, 0x2e, 0xac, 0xa9, 0xf3, 0xa5, 0x58, 0xca, 0x8c, 0x5d, 0xcf, 0x38, 0x0a, 0x2f, 0xd0,
	0x65, 0xf7, 0x7d, 0x8b, 0x3e, 0x62, 0xe5, 0xb1, 0x13, 0x1c, 0x53, 0x08, 0x8b, 0xae, 0x92, 0xcc,
	0x77, 0xe6, 0x97, 0x73, 0x8e, 0x67, 0x12, 0x58, 0x57, 0x01, 0x77, 0x51, 0xa0, 0xba, 0xdc, 0xe9,
	0xef, 0xee, 0xc4, 0xaf, 0x8e, 0xbe, 0x0a, 0x50, 0x55, 0x83, 0xd0, 0xd7, 0x3e, 0x59, 0x1c, 0x8d,
	0xab, 0xfd, 0xdd, 0xff, 0x2a, 0x63, 0xe2, 0x8c, 0x8e, 0xbe, 0x83, 0xf2, 0x11, 0x4a, 0x54, 0x9e,
	0x6a, 0x7b, 0x02, 0x19, 0xaa, 0xc0, 0x97, 0x0a, 0xc9, 0x1e, 0x2c, 0x44, 0xd2, 0x1b, 0x68, 0x4f,
	0x60, 0xc5, 0xda, 0xb4, 0xb6, 0x8b, 0x4f, 0x57, 0xab, 0x59, 0x62, 0xb5, 0xe5, 0x89, 0xa0, 0x87,
	0x0d, 0xa9, 0xd9, 0x48, 0x48, 0xdf, 0xc3, 0x72, 0x2d, 0x0a, 0x43, 0x94, 0xfa, 0x84, 0x5f, 0x61,
	0x98, 0x85, 0xf5, 0xe2, 0x05, 0x19, 0x89, 0x89, 0xb0, 0xa1, 0x30, 0x03, 0xab, 0x07, 0xbe, 0x7b,
	0x99, 0x85, 0x61, 0xbc, 0x70, 0x1f, 0xd8, 0x50, 0x48, 0x5f, 0x41, 0xa9, 0x89, 0xba, 0xd1, 0x19,
	0x51, 0x9e, 0xc0, 0x9c, 0x44, 0xed, 0x75, 0x26, 0x21, 0x12, 0x15, 0x3d, 0x83, 0x15, 0xe3, 0xa2,
	0x19, 0x09, 0x13, 0x4d, 0x8d, 0x40, 0xfb, 0x50, 0x90, 0x91, 0x30, 0xae, 0xd5, 0x24, 0xd8, 0xb5,
	0x92, 0xba, 0xb0, 0x79, 0xca, 0x07, 0xed, 0x90, 0x4b, 0xc5, 0x5d, 0xed, 0xf9, 0x52, 0x9d, 0x63,
	0xd8, 0x42, 0xd7, 0x97, 0xd7, 0x1e, 0x5f, 0xc3, 0x5f, 0x82, 0x0f, 0xf4, 0x20, 0xc0, 0x50, 0x99,
	0xc9, 0x24, 0x7e, 0x4e, 0x4e, 0xbf, 0x59, 0xf0, 0x8f, 0xed, 0xba, 0x7e, 0x24, 0xf5, 0x29, 0xaa,
	0xcb, 0x03, 0xae, 0xf9, 0xa1, 0xd7, 0xd3, 0x18, 0x92, 0x67, 0x00, 0x3c, 0x19, 0x38, 0xb7, 0x75,
	0x90, 0x6e, 0x6c, 0x74, 0x58, 0x81, 0x0f, 0xdf, 0x92, 0x7d, 0x58, 0x1d, 0xee, 0x33, 0x27, 0xae,
	0xc3, 0x35, 0x77, 0xba, 0x3d, 0xfe, 0x45, 0x55, 0xa6, 0x37, 0xad, 0xed, 0x12, 0x5b, 0xe6, 0xb9,
	0xef, 0x8b, 0x67, 0xf4, 0x87, 0x05, 0x7f, 0xe7, 0x8c, 0x90, 0x97, 0x50, 0xd4, 0xd7, 0xf1, 0x53,
	0x0f, 0xff, 0x8e, 0x7b, 0xc8, 0xf4, 0x73, 0x3c, 0xc5, 0xb2, 0x7a, 0xf2, 0x3c, 0x4e, 0xa0, 0xbd,
	0x3e, 0x37, 0xbb, 0xa7, 0xcd, 0xee, 0x4a, 0x3e, 0xc1, 0x70, 0x7e, 0x3c, 0xc5, 0x32, 0xea, 0xb7,
	0x45, 0x28, 0x18, 0xe3, 0x9e, 0x46, 0x41, 0x3f, 0xc1, 0xff, 0x39, 0x6b, 0x2d, 0x1d, 0x22, 0x17,
	0x0c, 0xbf, 0x46, 0xa8, 0x34, 0x79, 0x01, 0xf3, 0x5d, 0x53, 0x5a, 0x6a, 0x71, 0xeb, 0xb7, 0x35,
	0x8d, 0xf7, 0xcb, 0xd2, 0x2d, 0x94, 0xc1, 0xfa, 0x2d, 0xf0, 0xf4, 0x19, 0xef, 0xc2, 0x6c, 0x6c,
	0x25, 0x65, 0xaf, 0xdf, 0xc9, 0x66, 0x46, 0x4a, 0x7f, 0x5a, 0xb0, 0x96, 0x9b, 0x7c, 0x88, 0x30,
	0xbc, 0xfa, 0x13, 0x86, 0xc9, 0x1a, 0x14, 0x84, 0x27, 0x1d, 0x73, 0x4a, 0x4d, 0xab, 0xb3, 0x6c,
	0x41, 0x78, 0xd2, 0x1c, 0x7a, 0xb2, 0x01, 0x45, 0xc1, 0x07, 0x4e, 0x88, 0x2a, 0xea, 0x69, 0x55,
	0x99, 0x31, 0x4f, 0x1c, 0x04, 0x1f, 0xb0, 0x64, 0x85, 0xac, 0xc0, 0xbc, 0xdf, 0xed, 0x2a, 0xd4,
	0x95, 0x59, 0x33, 0x4b, 0x3f, 0xd1, 0xfe, 0x8d, 0x8e, 0x53, 0xc7, 0x37, 0x5a, 0x98, 0xb9, 0x67,
	0x0b, 0x64, 0x0b, 0x4a, 0xda, 0xd7, 0xbc, 0x37, 0x72, 0x93, 0x9c, 0xbf, 0x45, 0xb3, 0x98, 0xfa,
	0xa1, 0x0c, 0x48, 0x72, 0x5d, 0xc7, 0x0a, 0xda, 0x80, 0xa2, 0xd2, 0x3c, 0xd4, 0x69, 0x4a, 0x2b,
	0x89, 0x61, 0x96, 0x92, 0x9c, 0x6b, 0x50, 0x40, 0xd9, 0xc9, 0x94, 0x50, 0x62, 0x0b, 0x28, 0x3b,
	0x66, 0x48, 0xdf, 0x40, 0x79, 0x8c, 0x99, 0x46, 0x78, 0x04, 0x73, 0x43, 0x5c, 0x9c, 0xa1, 0x3c,
	0x9e, 0x21, 0xf9, 0x3d, 0x4c, 0x14, 0x23, 0x42, 0xee, 0x28, 0x64, 0x08, 0xd6, 0xdd, 0x84, 0xc7,
	0xdf, 0x2d, 0x28, 0xdb, 0x37, 0x2f, 0x1a, 0x79, 0x00, 0xd4, 0xae, 0xd5, 0xce, 0x2e, 0x9a, 0x6d,
	0xe7, 0xb4, 0xde, 0x3a, 0x76, 0x0e, 0xec, 0xb6, 0xed, 0x1c, 0x9e, 0xd8, 0x47, 0xce, 0x45, 0xb3,
	0x75, 0x5e, 0xaf, 0x35, 0x0e, 0x1b, 0xf5, 0x83, 0xa5, 0x29, 0xf2, 0x10, 0xb6, 0x6e, 0xd1, 0xb5,
	0x99, 0xdd, 0x6c, 0xd9, 0xb5, 0x76, 0xe3, 0xac, 0xd9, 0x5a, 0xb2, 0xee, 0x00, 0xc6, 0x9a, 0x8f,
	0x76, 0xa2, 0x9b, 0xfe, 0x3c, 0x6f, 0xfe, 0x4c, 0xf6, 0x7e, 0x05, 0x00, 0x00, 0xff, 0xff, 0x59,
	0xfb, 0xe1, 0x78, 0x95, 0x06, 0x00, 0x00,
}
