// Code generated by protoc-gen-go. DO NOT EDIT.
// source: spacemesh/v1/tx.proto

package spacemesh_v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("spacemesh/v1/tx.proto", fileDescriptor_c8a385573c79cfb7) }

var fileDescriptor_c8a385573c79cfb7 = []byte{
	// 179 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0xd0, 0xb1, 0x0a, 0xc2, 0x30,
	0x10, 0x80, 0x61, 0x74, 0x70, 0x08, 0x2e, 0x06, 0x44, 0xa8, 0xbb, 0x2e, 0x9a, 0x5a, 0x7d, 0x13,
	0xe3, 0x2e, 0x69, 0x3d, 0xb0, 0x43, 0x9b, 0x98, 0xbb, 0x86, 0xfa, 0xaa, 0x3e, 0x8d, 0xd0, 0xa8,
	0x84, 0x46, 0xa9, 0xeb, 0xdd, 0xc7, 0xfd, 0x70, 0x6c, 0x8e, 0x46, 0x15, 0x50, 0x01, 0x5e, 0x53,
	0x97, 0xa5, 0xd4, 0x0a, 0x63, 0x35, 0x69, 0x3e, 0xfd, 0x8c, 0x85, 0xcb, 0x92, 0x65, 0x0f, 0x9d,
	0xe9, 0x6e, 0x00, 0x3d, 0xdd, 0x3f, 0xc6, 0x8c, 0x9f, 0xac, 0xaa, 0x51, 0x15, 0x54, 0xea, 0x5a,
	0x82, 0x75, 0x65, 0x01, 0xfc, 0xc2, 0x66, 0xb2, 0xc9, 0xab, 0x92, 0x82, 0x1d, 0x5f, 0x89, 0xf0,
	0xae, 0x88, 0xc0, 0x11, 0x6e, 0x0d, 0x20, 0x25, 0xeb, 0x41, 0x87, 0x46, 0xd7, 0xd8, 0x55, 0x82,
	0x31, 0x4a, 0x52, 0x04, 0xfd, 0x4a, 0x04, 0x7e, 0x54, 0xbe, 0xb8, 0x57, 0xa5, 0x65, 0x8b, 0x68,
	0x29, 0xc9, 0x82, 0xaa, 0xf8, 0x66, 0xe0, 0x86, 0x67, 0xef, 0xe2, 0xf6, 0x4f, 0xed, 0xbb, 0xbb,
	0x51, 0x3e, 0xe9, 0x7e, 0x7c, 0x78, 0x06, 0x00, 0x00, 0xff, 0xff, 0x19, 0x06, 0x2f, 0xf4, 0xa7,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TransactionServiceClient is the client API for TransactionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TransactionServiceClient interface {
	// Submit a new tx to the node for processing. The response
	// TransactionState message contains both the txid of the new tx, as well
	// as whether or not it was admitted into the mempool.
	SubmitTransaction(ctx context.Context, in *SubmitTransactionRequest, opts ...grpc.CallOption) (*SubmitTransactionResponse, error)
	// Returns current tx state for one or more txs which indicates if a tx is
	// on the mesh, on its way to the mesh or was rejected and will never get
	// to the mesh
	TransactionsState(ctx context.Context, in *TransactionsStateRequest, opts ...grpc.CallOption) (*TransactionsStateResponse, error)
	// Returns tx state for one or more txs every time the tx state changes for
	// one of these txs
	TransactionsStateStream(ctx context.Context, in *TransactionsStateStreamRequest, opts ...grpc.CallOption) (TransactionService_TransactionsStateStreamClient, error)
}

type transactionServiceClient struct {
	cc *grpc.ClientConn
}

func NewTransactionServiceClient(cc *grpc.ClientConn) TransactionServiceClient {
	return &transactionServiceClient{cc}
}

func (c *transactionServiceClient) SubmitTransaction(ctx context.Context, in *SubmitTransactionRequest, opts ...grpc.CallOption) (*SubmitTransactionResponse, error) {
	out := new(SubmitTransactionResponse)
	err := c.cc.Invoke(ctx, "/spacemesh.v1.TransactionService/SubmitTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) TransactionsState(ctx context.Context, in *TransactionsStateRequest, opts ...grpc.CallOption) (*TransactionsStateResponse, error) {
	out := new(TransactionsStateResponse)
	err := c.cc.Invoke(ctx, "/spacemesh.v1.TransactionService/TransactionsState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) TransactionsStateStream(ctx context.Context, in *TransactionsStateStreamRequest, opts ...grpc.CallOption) (TransactionService_TransactionsStateStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TransactionService_serviceDesc.Streams[0], "/spacemesh.v1.TransactionService/TransactionsStateStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &transactionServiceTransactionsStateStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TransactionService_TransactionsStateStreamClient interface {
	Recv() (*TransactionsStateStreamResponse, error)
	grpc.ClientStream
}

type transactionServiceTransactionsStateStreamClient struct {
	grpc.ClientStream
}

func (x *transactionServiceTransactionsStateStreamClient) Recv() (*TransactionsStateStreamResponse, error) {
	m := new(TransactionsStateStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TransactionServiceServer is the server API for TransactionService service.
type TransactionServiceServer interface {
	// Submit a new tx to the node for processing. The response
	// TransactionState message contains both the txid of the new tx, as well
	// as whether or not it was admitted into the mempool.
	SubmitTransaction(context.Context, *SubmitTransactionRequest) (*SubmitTransactionResponse, error)
	// Returns current tx state for one or more txs which indicates if a tx is
	// on the mesh, on its way to the mesh or was rejected and will never get
	// to the mesh
	TransactionsState(context.Context, *TransactionsStateRequest) (*TransactionsStateResponse, error)
	// Returns tx state for one or more txs every time the tx state changes for
	// one of these txs
	TransactionsStateStream(*TransactionsStateStreamRequest, TransactionService_TransactionsStateStreamServer) error
}

// UnimplementedTransactionServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTransactionServiceServer struct {
}

func (*UnimplementedTransactionServiceServer) SubmitTransaction(ctx context.Context, req *SubmitTransactionRequest) (*SubmitTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitTransaction not implemented")
}
func (*UnimplementedTransactionServiceServer) TransactionsState(ctx context.Context, req *TransactionsStateRequest) (*TransactionsStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransactionsState not implemented")
}
func (*UnimplementedTransactionServiceServer) TransactionsStateStream(req *TransactionsStateStreamRequest, srv TransactionService_TransactionsStateStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method TransactionsStateStream not implemented")
}

func RegisterTransactionServiceServer(s *grpc.Server, srv TransactionServiceServer) {
	s.RegisterService(&_TransactionService_serviceDesc, srv)
}

func _TransactionService_SubmitTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).SubmitTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spacemesh.v1.TransactionService/SubmitTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).SubmitTransaction(ctx, req.(*SubmitTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_TransactionsState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionsStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).TransactionsState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spacemesh.v1.TransactionService/TransactionsState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).TransactionsState(ctx, req.(*TransactionsStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_TransactionsStateStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TransactionsStateStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TransactionServiceServer).TransactionsStateStream(m, &transactionServiceTransactionsStateStreamServer{stream})
}

type TransactionService_TransactionsStateStreamServer interface {
	Send(*TransactionsStateStreamResponse) error
	grpc.ServerStream
}

type transactionServiceTransactionsStateStreamServer struct {
	grpc.ServerStream
}

func (x *transactionServiceTransactionsStateStreamServer) Send(m *TransactionsStateStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _TransactionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "spacemesh.v1.TransactionService",
	HandlerType: (*TransactionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitTransaction",
			Handler:    _TransactionService_SubmitTransaction_Handler,
		},
		{
			MethodName: "TransactionsState",
			Handler:    _TransactionService_TransactionsState_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TransactionsStateStream",
			Handler:       _TransactionService_TransactionsStateStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "spacemesh/v1/tx.proto",
}
