// Code generated by protoc-gen-go. DO NOT EDIT.
// source: spacemesh/v1/tx_types.proto

package spacemesh_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	status "google.golang.org/genproto/googleapis/rpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TransactionState_TransactionState int32

const (
	TransactionState_TRANSACTION_STATE_UNSPECIFIED        TransactionState_TransactionState = 0
	TransactionState_TRANSACTION_STATE_REJECTED           TransactionState_TransactionState = 1
	TransactionState_TRANSACTION_STATE_INSUFFICIENT_FUNDS TransactionState_TransactionState = 2
	TransactionState_TRANSACTION_STATE_CONFLICTING        TransactionState_TransactionState = 3
	TransactionState_TRANSACTION_STATE_MEMPOOL            TransactionState_TransactionState = 4
	TransactionState_TRANSACTION_STATE_MESH               TransactionState_TransactionState = 5
	TransactionState_TRANSACTION_STATE_PROCESSED          TransactionState_TransactionState = 6
)

var TransactionState_TransactionState_name = map[int32]string{
	0: "TRANSACTION_STATE_UNSPECIFIED",
	1: "TRANSACTION_STATE_REJECTED",
	2: "TRANSACTION_STATE_INSUFFICIENT_FUNDS",
	3: "TRANSACTION_STATE_CONFLICTING",
	4: "TRANSACTION_STATE_MEMPOOL",
	5: "TRANSACTION_STATE_MESH",
	6: "TRANSACTION_STATE_PROCESSED",
}

var TransactionState_TransactionState_value = map[string]int32{
	"TRANSACTION_STATE_UNSPECIFIED":        0,
	"TRANSACTION_STATE_REJECTED":           1,
	"TRANSACTION_STATE_INSUFFICIENT_FUNDS": 2,
	"TRANSACTION_STATE_CONFLICTING":        3,
	"TRANSACTION_STATE_MEMPOOL":            4,
	"TRANSACTION_STATE_MESH":               5,
	"TRANSACTION_STATE_PROCESSED":          6,
}

func (x TransactionState_TransactionState) String() string {
	return proto.EnumName(TransactionState_TransactionState_name, int32(x))
}

func (TransactionState_TransactionState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_167f5cee1628300f, []int{7, 0}
}

type TransactionsIds struct {
	TransactionId        []*TransactionId `protobuf:"bytes,1,rep,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *TransactionsIds) Reset()         { *m = TransactionsIds{} }
func (m *TransactionsIds) String() string { return proto.CompactTextString(m) }
func (*TransactionsIds) ProtoMessage()    {}
func (*TransactionsIds) Descriptor() ([]byte, []int) {
	return fileDescriptor_167f5cee1628300f, []int{0}
}

func (m *TransactionsIds) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionsIds.Unmarshal(m, b)
}
func (m *TransactionsIds) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionsIds.Marshal(b, m, deterministic)
}
func (m *TransactionsIds) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionsIds.Merge(m, src)
}
func (m *TransactionsIds) XXX_Size() int {
	return xxx_messageInfo_TransactionsIds.Size(m)
}
func (m *TransactionsIds) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionsIds.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionsIds proto.InternalMessageInfo

func (m *TransactionsIds) GetTransactionId() []*TransactionId {
	if m != nil {
		return m.TransactionId
	}
	return nil
}

type SubmitTransactionRequest struct {
	Tx                   *Transaction `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SubmitTransactionRequest) Reset()         { *m = SubmitTransactionRequest{} }
func (m *SubmitTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*SubmitTransactionRequest) ProtoMessage()    {}
func (*SubmitTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_167f5cee1628300f, []int{1}
}

func (m *SubmitTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitTransactionRequest.Unmarshal(m, b)
}
func (m *SubmitTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitTransactionRequest.Marshal(b, m, deterministic)
}
func (m *SubmitTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitTransactionRequest.Merge(m, src)
}
func (m *SubmitTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_SubmitTransactionRequest.Size(m)
}
func (m *SubmitTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitTransactionRequest proto.InternalMessageInfo

func (m *SubmitTransactionRequest) GetTx() *Transaction {
	if m != nil {
		return m.Tx
	}
	return nil
}

type SubmitTransactionResponse struct {
	Status               *status.Status    `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Txstate              *TransactionState `protobuf:"bytes,2,opt,name=txstate,proto3" json:"txstate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SubmitTransactionResponse) Reset()         { *m = SubmitTransactionResponse{} }
func (m *SubmitTransactionResponse) String() string { return proto.CompactTextString(m) }
func (*SubmitTransactionResponse) ProtoMessage()    {}
func (*SubmitTransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_167f5cee1628300f, []int{2}
}

func (m *SubmitTransactionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitTransactionResponse.Unmarshal(m, b)
}
func (m *SubmitTransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitTransactionResponse.Marshal(b, m, deterministic)
}
func (m *SubmitTransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitTransactionResponse.Merge(m, src)
}
func (m *SubmitTransactionResponse) XXX_Size() int {
	return xxx_messageInfo_SubmitTransactionResponse.Size(m)
}
func (m *SubmitTransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitTransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitTransactionResponse proto.InternalMessageInfo

func (m *SubmitTransactionResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *SubmitTransactionResponse) GetTxstate() *TransactionState {
	if m != nil {
		return m.Txstate
	}
	return nil
}

type TransactionsStateRequest struct {
	TransactionId        []*TransactionId `protobuf:"bytes,1,rep,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *TransactionsStateRequest) Reset()         { *m = TransactionsStateRequest{} }
func (m *TransactionsStateRequest) String() string { return proto.CompactTextString(m) }
func (*TransactionsStateRequest) ProtoMessage()    {}
func (*TransactionsStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_167f5cee1628300f, []int{3}
}

func (m *TransactionsStateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionsStateRequest.Unmarshal(m, b)
}
func (m *TransactionsStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionsStateRequest.Marshal(b, m, deterministic)
}
func (m *TransactionsStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionsStateRequest.Merge(m, src)
}
func (m *TransactionsStateRequest) XXX_Size() int {
	return xxx_messageInfo_TransactionsStateRequest.Size(m)
}
func (m *TransactionsStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionsStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionsStateRequest proto.InternalMessageInfo

func (m *TransactionsStateRequest) GetTransactionId() []*TransactionId {
	if m != nil {
		return m.TransactionId
	}
	return nil
}

type TransactionsStateResponse struct {
	TransactionsState    []*TransactionState `protobuf:"bytes,1,rep,name=transactions_state,json=transactionsState,proto3" json:"transactions_state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *TransactionsStateResponse) Reset()         { *m = TransactionsStateResponse{} }
func (m *TransactionsStateResponse) String() string { return proto.CompactTextString(m) }
func (*TransactionsStateResponse) ProtoMessage()    {}
func (*TransactionsStateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_167f5cee1628300f, []int{4}
}

func (m *TransactionsStateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionsStateResponse.Unmarshal(m, b)
}
func (m *TransactionsStateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionsStateResponse.Marshal(b, m, deterministic)
}
func (m *TransactionsStateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionsStateResponse.Merge(m, src)
}
func (m *TransactionsStateResponse) XXX_Size() int {
	return xxx_messageInfo_TransactionsStateResponse.Size(m)
}
func (m *TransactionsStateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionsStateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionsStateResponse proto.InternalMessageInfo

func (m *TransactionsStateResponse) GetTransactionsState() []*TransactionState {
	if m != nil {
		return m.TransactionsState
	}
	return nil
}

type TransactionsStateStreamRequest struct {
	TransactionId        []*TransactionId `protobuf:"bytes,1,rep,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *TransactionsStateStreamRequest) Reset()         { *m = TransactionsStateStreamRequest{} }
func (m *TransactionsStateStreamRequest) String() string { return proto.CompactTextString(m) }
func (*TransactionsStateStreamRequest) ProtoMessage()    {}
func (*TransactionsStateStreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_167f5cee1628300f, []int{5}
}

func (m *TransactionsStateStreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionsStateStreamRequest.Unmarshal(m, b)
}
func (m *TransactionsStateStreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionsStateStreamRequest.Marshal(b, m, deterministic)
}
func (m *TransactionsStateStreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionsStateStreamRequest.Merge(m, src)
}
func (m *TransactionsStateStreamRequest) XXX_Size() int {
	return xxx_messageInfo_TransactionsStateStreamRequest.Size(m)
}
func (m *TransactionsStateStreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionsStateStreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionsStateStreamRequest proto.InternalMessageInfo

func (m *TransactionsStateStreamRequest) GetTransactionId() []*TransactionId {
	if m != nil {
		return m.TransactionId
	}
	return nil
}

type TransactionsStateStreamResponse struct {
	TransactionsState    []*TransactionState `protobuf:"bytes,1,rep,name=transactions_state,json=transactionsState,proto3" json:"transactions_state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *TransactionsStateStreamResponse) Reset()         { *m = TransactionsStateStreamResponse{} }
func (m *TransactionsStateStreamResponse) String() string { return proto.CompactTextString(m) }
func (*TransactionsStateStreamResponse) ProtoMessage()    {}
func (*TransactionsStateStreamResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_167f5cee1628300f, []int{6}
}

func (m *TransactionsStateStreamResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionsStateStreamResponse.Unmarshal(m, b)
}
func (m *TransactionsStateStreamResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionsStateStreamResponse.Marshal(b, m, deterministic)
}
func (m *TransactionsStateStreamResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionsStateStreamResponse.Merge(m, src)
}
func (m *TransactionsStateStreamResponse) XXX_Size() int {
	return xxx_messageInfo_TransactionsStateStreamResponse.Size(m)
}
func (m *TransactionsStateStreamResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionsStateStreamResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionsStateStreamResponse proto.InternalMessageInfo

func (m *TransactionsStateStreamResponse) GetTransactionsState() []*TransactionState {
	if m != nil {
		return m.TransactionsState
	}
	return nil
}

// TransactionState is the "journey" of a tx from mempool to block inclusion to
// mesh to STF processing. To know whether or not the tx actually succeeded,
// and its side effects, check the Receipt in the GlobalStateService.
type TransactionState struct {
	Id                   *TransactionId                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	State                TransactionState_TransactionState `protobuf:"varint,2,opt,name=state,proto3,enum=spacemesh.v1.TransactionState_TransactionState" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *TransactionState) Reset()         { *m = TransactionState{} }
func (m *TransactionState) String() string { return proto.CompactTextString(m) }
func (*TransactionState) ProtoMessage()    {}
func (*TransactionState) Descriptor() ([]byte, []int) {
	return fileDescriptor_167f5cee1628300f, []int{7}
}

func (m *TransactionState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionState.Unmarshal(m, b)
}
func (m *TransactionState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionState.Marshal(b, m, deterministic)
}
func (m *TransactionState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionState.Merge(m, src)
}
func (m *TransactionState) XXX_Size() int {
	return xxx_messageInfo_TransactionState.Size(m)
}
func (m *TransactionState) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionState.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionState proto.InternalMessageInfo

func (m *TransactionState) GetId() *TransactionId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *TransactionState) GetState() TransactionState_TransactionState {
	if m != nil {
		return m.State
	}
	return TransactionState_TRANSACTION_STATE_UNSPECIFIED
}

func init() {
	proto.RegisterEnum("spacemesh.v1.TransactionState_TransactionState", TransactionState_TransactionState_name, TransactionState_TransactionState_value)
	proto.RegisterType((*TransactionsIds)(nil), "spacemesh.v1.TransactionsIds")
	proto.RegisterType((*SubmitTransactionRequest)(nil), "spacemesh.v1.SubmitTransactionRequest")
	proto.RegisterType((*SubmitTransactionResponse)(nil), "spacemesh.v1.SubmitTransactionResponse")
	proto.RegisterType((*TransactionsStateRequest)(nil), "spacemesh.v1.TransactionsStateRequest")
	proto.RegisterType((*TransactionsStateResponse)(nil), "spacemesh.v1.TransactionsStateResponse")
	proto.RegisterType((*TransactionsStateStreamRequest)(nil), "spacemesh.v1.TransactionsStateStreamRequest")
	proto.RegisterType((*TransactionsStateStreamResponse)(nil), "spacemesh.v1.TransactionsStateStreamResponse")
	proto.RegisterType((*TransactionState)(nil), "spacemesh.v1.TransactionState")
}

func init() { proto.RegisterFile("spacemesh/v1/tx_types.proto", fileDescriptor_167f5cee1628300f) }

var fileDescriptor_167f5cee1628300f = []byte{
	// 452 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x94, 0xc1, 0x8f, 0x93, 0x40,
	0x18, 0xc5, 0x85, 0xba, 0x35, 0xf9, 0x56, 0x57, 0x9c, 0x83, 0xd2, 0x36, 0xdb, 0x5d, 0x89, 0x87,
	0xaa, 0x09, 0x64, 0xeb, 0xc5, 0x6b, 0xa5, 0x83, 0x8e, 0xd9, 0x42, 0x33, 0x33, 0xbd, 0x4a, 0xd8,
	0x32, 0x59, 0x6b, 0x6c, 0x41, 0x66, 0xba, 0xa9, 0x47, 0x4f, 0xfe, 0xd7, 0xc6, 0x2c, 0xa0, 0xc5,
	0x85, 0xba, 0x97, 0xee, 0x0d, 0x78, 0xbf, 0xef, 0xbd, 0xef, 0x4d, 0xc8, 0x40, 0x4f, 0xa6, 0xd1,
	0x5c, 0x2c, 0x85, 0xfc, 0xec, 0x5c, 0x9d, 0x39, 0x6a, 0x13, 0xaa, 0xef, 0xa9, 0x90, 0x76, 0x9a,
	0x25, 0x2a, 0x41, 0x0f, 0xff, 0x8a, 0xf6, 0xd5, 0x59, 0xf7, 0xd9, 0x65, 0x92, 0x5c, 0x7e, 0x15,
	0x4e, 0x96, 0xce, 0x1d, 0xa9, 0x22, 0xb5, 0x2e, 0xb1, 0xae, 0xf9, 0xaf, 0xc7, 0xd6, 0xc0, 0x9a,
	0xc1, 0x63, 0x9e, 0x45, 0x2b, 0x19, 0xcd, 0xd5, 0x22, 0x59, 0x49, 0x12, 0x4b, 0xf4, 0x0e, 0x8e,
	0xd4, 0xf6, 0x53, 0xb8, 0x88, 0x4d, 0xed, 0xb4, 0x35, 0x38, 0x1c, 0xf6, 0xec, 0x6a, 0x98, 0x5d,
	0x19, 0x23, 0x31, 0x7d, 0xa4, 0xaa, 0xaf, 0x16, 0x06, 0x93, 0xad, 0x2f, 0x96, 0x0b, 0x55, 0xa1,
	0xa8, 0xf8, 0xb6, 0x16, 0x52, 0xa1, 0x97, 0xa0, 0xab, 0x8d, 0xa9, 0x9d, 0x6a, 0x83, 0xc3, 0x61,
	0x67, 0xa7, 0x27, 0xd5, 0xd5, 0xc6, 0xfa, 0xa1, 0x41, 0xa7, 0xc1, 0x47, 0xa6, 0xc9, 0x4a, 0x0a,
	0xf4, 0x0a, 0xda, 0x45, 0xcb, 0xd2, 0x0c, 0xd9, 0x45, 0x7f, 0x3b, 0x4b, 0xe7, 0x36, 0xcb, 0x15,
	0x5a, 0x12, 0xe8, 0x2d, 0x3c, 0x50, 0x9b, 0xeb, 0x67, 0x61, 0xea, 0x39, 0xdc, 0xdf, 0x99, 0x7c,
	0x3d, 0x29, 0xe8, 0x1f, 0xdc, 0xfa, 0x04, 0x66, 0xf5, 0x84, 0x0a, 0xb5, 0xac, 0xb2, 0x8f, 0xa3,
	0xfa, 0x02, 0x9d, 0x06, 0xff, 0xb2, 0xe2, 0x04, 0x50, 0x85, 0x96, 0x61, 0xd1, 0xa0, 0x08, 0xb9,
	0xad, 0xc1, 0x13, 0x75, 0xd3, 0xd6, 0x8a, 0xa1, 0x5f, 0xcb, 0x62, 0x2a, 0x13, 0xd1, 0x72, 0x9f,
	0x8d, 0x52, 0x38, 0xd9, 0x99, 0x72, 0x37, 0xbd, 0x7e, 0xb6, 0xc0, 0xb8, 0xc9, 0xa1, 0xd7, 0xa0,
	0xe7, 0xeb, 0x6b, 0xb7, 0xad, 0xaf, 0x2f, 0x62, 0x84, 0xe1, 0x60, 0xfb, 0x77, 0x1c, 0x0d, 0x9d,
	0xff, 0xef, 0x50, 0x5f, 0xaa, 0x98, 0xb6, 0x7e, 0x69, 0x0d, 0x8b, 0x3c, 0x87, 0x63, 0x4e, 0x47,
	0x3e, 0x1b, 0xb9, 0x9c, 0x04, 0x7e, 0xc8, 0xf8, 0x88, 0xe3, 0x70, 0xe6, 0xb3, 0x29, 0x76, 0x89,
	0x47, 0xf0, 0xd8, 0xb8, 0x87, 0xfa, 0xd0, 0xad, 0x23, 0x14, 0x7f, 0xc4, 0x2e, 0xc7, 0x63, 0x43,
	0x43, 0x03, 0x78, 0x51, 0xd7, 0x89, 0xcf, 0x66, 0x9e, 0x47, 0x5c, 0x82, 0x7d, 0x1e, 0x7a, 0x33,
	0x7f, 0xcc, 0x0c, 0xbd, 0x39, 0xcc, 0x0d, 0x7c, 0xef, 0x9c, 0xb8, 0x9c, 0xf8, 0xef, 0x8d, 0x16,
	0x3a, 0x86, 0x4e, 0x1d, 0x99, 0xe0, 0xc9, 0x34, 0x08, 0xce, 0x8d, 0xfb, 0xa8, 0x0b, 0x4f, 0x9b,
	0x64, 0xf6, 0xc1, 0x38, 0x40, 0x27, 0xd0, 0xab, 0x6b, 0x53, 0x1a, 0xb8, 0x98, 0x31, 0x3c, 0x36,
	0xda, 0x17, 0xed, 0xfc, 0x5a, 0x79, 0xf3, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xd8, 0x4c, 0x56, 0x3f,
	0xb6, 0x04, 0x00, 0x00,
}
