// Code generated by protoc-gen-go. DO NOT EDIT.
// source: spacemesh/mesh.proto

package spacemesh

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("spacemesh/mesh.proto", fileDescriptor_5c73b39733a5abc3) }

var fileDescriptor_5c73b39733a5abc3 = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x8e, 0xcd, 0x4a, 0x03, 0x31,
	0x14, 0x85, 0x11, 0x51, 0x30, 0x23, 0x22, 0x43, 0x15, 0x19, 0xdf, 0x21, 0x23, 0x8a, 0x0b, 0x51,
	0xdc, 0x48, 0xd1, 0x82, 0x2d, 0xc2, 0xf4, 0x05, 0xd2, 0x78, 0xec, 0x04, 0x9a, 0x1f, 0x72, 0xef,
	0x88, 0xf3, 0x7a, 0x3e, 0x99, 0x34, 0x83, 0xa3, 0x1b, 0x17, 0x71, 0x93, 0xc5, 0xc9, 0xf9, 0xbe,
	0x7b, 0xc4, 0x84, 0x82, 0xd2, 0xb0, 0xa0, 0xb6, 0xde, 0x3e, 0x32, 0x44, 0xcf, 0xbe, 0x3c, 0x18,
	0xd3, 0xea, 0x7c, 0xed, 0xfd, 0x7a, 0x83, 0x3a, 0x7d, 0xac, 0xba, 0xb7, 0x1a, 0x36, 0x70, 0x3f,
	0xf4, 0xaa, 0x93, 0x1f, 0x9a, 0xfb, 0x00, 0x1a, 0xe2, 0xcb, 0xcf, 0x5d, 0x51, 0xcc, 0x41, 0x6d,
	0x83, 0xf8, 0x6e, 0x34, 0xca, 0x5b, 0x51, 0x3c, 0xc2, 0x81, 0x0c, 0x2d, 0x8d, 0x45, 0x79, 0x2a,
	0x07, 0xa7, 0xfc, 0x76, 0xca, 0xe9, 0xd6, 0x59, 0x4d, 0xe4, 0xa8, 0x93, 0x8d, 0xb1, 0x61, 0x83,
	0x99, 0xe3, 0xf2, 0x4e, 0x1c, 0x3e, 0x74, 0x31, 0xc2, 0xf1, 0xb3, 0xea, 0x11, 0xff, 0x4d, 0x4f,
	0x83, 0xd7, 0x6d, 0x26, 0x7d, 0x2d, 0xf6, 0x16, 0xe0, 0xd9, 0x6b, 0x26, 0x76, 0x2f, 0x8e, 0xd2,
	0xb5, 0x45, 0x67, 0xd3, 0x66, 0xca, 0xe4, 0x9f, 0xc4, 0xd9, 0x5c, 0x7d, 0x2c, 0xa3, 0x72, 0xa4,
	0x34, 0x1b, 0xef, 0xe8, 0x05, 0xb1, 0x81, 0xf6, 0x2e, 0x77, 0xc9, 0x8d, 0x28, 0xd2, 0x82, 0x86,
	0x23, 0x94, 0xfd, 0x13, 0x3e, 0xfe, 0x05, 0xa7, 0xfe, 0xc5, 0xce, 0x6a, 0x3f, 0x75, 0xae, 0xbe,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x75, 0x7d, 0x0a, 0x90, 0x22, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MeshServiceClient is the client API for MeshService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MeshServiceClient interface {
	// Network genesis time as unix epoch time
	GenesisTime(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*SimpleInt, error)
	// Current layer number
	CurrentLayer(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*SimpleInt, error)
	// Current epoch number
	CurrentEpoch(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*SimpleInt, error)
	// Network ID
	NetId(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*SimpleInt, error)
	// Number of layers per epoch (a network parameter)
	EpochNumLayers(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*SimpleInt, error)
	// Number of transactions per second (a network parameter)
	MaxTransactionsPerSecond(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*SimpleInt, error)
	// Layer with blocks and transactions.
	// Sent each time layer data changes. Designed for heavy-duty clients.
	LayerStream(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (MeshService_LayerStreamClient, error)
}

type meshServiceClient struct {
	cc *grpc.ClientConn
}

func NewMeshServiceClient(cc *grpc.ClientConn) MeshServiceClient {
	return &meshServiceClient{cc}
}

func (c *meshServiceClient) GenesisTime(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*SimpleInt, error) {
	out := new(SimpleInt)
	err := c.cc.Invoke(ctx, "/spacemesh.MeshService/GenesisTime", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshServiceClient) CurrentLayer(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*SimpleInt, error) {
	out := new(SimpleInt)
	err := c.cc.Invoke(ctx, "/spacemesh.MeshService/CurrentLayer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshServiceClient) CurrentEpoch(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*SimpleInt, error) {
	out := new(SimpleInt)
	err := c.cc.Invoke(ctx, "/spacemesh.MeshService/CurrentEpoch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshServiceClient) NetId(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*SimpleInt, error) {
	out := new(SimpleInt)
	err := c.cc.Invoke(ctx, "/spacemesh.MeshService/NetId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshServiceClient) EpochNumLayers(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*SimpleInt, error) {
	out := new(SimpleInt)
	err := c.cc.Invoke(ctx, "/spacemesh.MeshService/EpochNumLayers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshServiceClient) MaxTransactionsPerSecond(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*SimpleInt, error) {
	out := new(SimpleInt)
	err := c.cc.Invoke(ctx, "/spacemesh.MeshService/MaxTransactionsPerSecond", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshServiceClient) LayerStream(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (MeshService_LayerStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MeshService_serviceDesc.Streams[0], "/spacemesh.MeshService/LayerStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &meshServiceLayerStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MeshService_LayerStreamClient interface {
	Recv() (*Layer, error)
	grpc.ClientStream
}

type meshServiceLayerStreamClient struct {
	grpc.ClientStream
}

func (x *meshServiceLayerStreamClient) Recv() (*Layer, error) {
	m := new(Layer)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MeshServiceServer is the server API for MeshService service.
type MeshServiceServer interface {
	// Network genesis time as unix epoch time
	GenesisTime(context.Context, *empty.Empty) (*SimpleInt, error)
	// Current layer number
	CurrentLayer(context.Context, *empty.Empty) (*SimpleInt, error)
	// Current epoch number
	CurrentEpoch(context.Context, *empty.Empty) (*SimpleInt, error)
	// Network ID
	NetId(context.Context, *empty.Empty) (*SimpleInt, error)
	// Number of layers per epoch (a network parameter)
	EpochNumLayers(context.Context, *empty.Empty) (*SimpleInt, error)
	// Number of transactions per second (a network parameter)
	MaxTransactionsPerSecond(context.Context, *empty.Empty) (*SimpleInt, error)
	// Layer with blocks and transactions.
	// Sent each time layer data changes. Designed for heavy-duty clients.
	LayerStream(*empty.Empty, MeshService_LayerStreamServer) error
}

// UnimplementedMeshServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMeshServiceServer struct {
}

func (*UnimplementedMeshServiceServer) GenesisTime(ctx context.Context, req *empty.Empty) (*SimpleInt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenesisTime not implemented")
}
func (*UnimplementedMeshServiceServer) CurrentLayer(ctx context.Context, req *empty.Empty) (*SimpleInt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CurrentLayer not implemented")
}
func (*UnimplementedMeshServiceServer) CurrentEpoch(ctx context.Context, req *empty.Empty) (*SimpleInt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CurrentEpoch not implemented")
}
func (*UnimplementedMeshServiceServer) NetId(ctx context.Context, req *empty.Empty) (*SimpleInt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NetId not implemented")
}
func (*UnimplementedMeshServiceServer) EpochNumLayers(ctx context.Context, req *empty.Empty) (*SimpleInt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EpochNumLayers not implemented")
}
func (*UnimplementedMeshServiceServer) MaxTransactionsPerSecond(ctx context.Context, req *empty.Empty) (*SimpleInt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MaxTransactionsPerSecond not implemented")
}
func (*UnimplementedMeshServiceServer) LayerStream(req *empty.Empty, srv MeshService_LayerStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method LayerStream not implemented")
}

func RegisterMeshServiceServer(s *grpc.Server, srv MeshServiceServer) {
	s.RegisterService(&_MeshService_serviceDesc, srv)
}

func _MeshService_GenesisTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServiceServer).GenesisTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spacemesh.MeshService/GenesisTime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServiceServer).GenesisTime(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshService_CurrentLayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServiceServer).CurrentLayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spacemesh.MeshService/CurrentLayer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServiceServer).CurrentLayer(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshService_CurrentEpoch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServiceServer).CurrentEpoch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spacemesh.MeshService/CurrentEpoch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServiceServer).CurrentEpoch(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshService_NetId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServiceServer).NetId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spacemesh.MeshService/NetId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServiceServer).NetId(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshService_EpochNumLayers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServiceServer).EpochNumLayers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spacemesh.MeshService/EpochNumLayers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServiceServer).EpochNumLayers(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshService_MaxTransactionsPerSecond_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServiceServer).MaxTransactionsPerSecond(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spacemesh.MeshService/MaxTransactionsPerSecond",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServiceServer).MaxTransactionsPerSecond(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshService_LayerStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MeshServiceServer).LayerStream(m, &meshServiceLayerStreamServer{stream})
}

type MeshService_LayerStreamServer interface {
	Send(*Layer) error
	grpc.ServerStream
}

type meshServiceLayerStreamServer struct {
	grpc.ServerStream
}

func (x *meshServiceLayerStreamServer) Send(m *Layer) error {
	return x.ServerStream.SendMsg(m)
}

var _MeshService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "spacemesh.MeshService",
	HandlerType: (*MeshServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenesisTime",
			Handler:    _MeshService_GenesisTime_Handler,
		},
		{
			MethodName: "CurrentLayer",
			Handler:    _MeshService_CurrentLayer_Handler,
		},
		{
			MethodName: "CurrentEpoch",
			Handler:    _MeshService_CurrentEpoch_Handler,
		},
		{
			MethodName: "NetId",
			Handler:    _MeshService_NetId_Handler,
		},
		{
			MethodName: "EpochNumLayers",
			Handler:    _MeshService_EpochNumLayers_Handler,
		},
		{
			MethodName: "MaxTransactionsPerSecond",
			Handler:    _MeshService_MaxTransactionsPerSecond_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "LayerStream",
			Handler:       _MeshService_LayerStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "spacemesh/mesh.proto",
}
