// Code generated by protoc-gen-go. DO NOT EDIT.
// source: spacemesh/types.proto

package spacemesh

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TransactionState_TransactionStateType int32

const (
	TransactionState_UNDEFINED          TransactionState_TransactionStateType = 0
	TransactionState_UNKNOWN            TransactionState_TransactionStateType = 1
	TransactionState_REJECTED           TransactionState_TransactionStateType = 2
	TransactionState_INSUFFICIENT_FUNDS TransactionState_TransactionStateType = 3
	TransactionState_CONFLICTING        TransactionState_TransactionStateType = 4
	TransactionState_PENDING            TransactionState_TransactionStateType = 5
	TransactionState_PROCESSED          TransactionState_TransactionStateType = 6
)

var TransactionState_TransactionStateType_name = map[int32]string{
	0: "UNDEFINED",
	1: "UNKNOWN",
	2: "REJECTED",
	3: "INSUFFICIENT_FUNDS",
	4: "CONFLICTING",
	5: "PENDING",
	6: "PROCESSED",
}

var TransactionState_TransactionStateType_value = map[string]int32{
	"UNDEFINED":          0,
	"UNKNOWN":            1,
	"REJECTED":           2,
	"INSUFFICIENT_FUNDS": 3,
	"CONFLICTING":        4,
	"PENDING":            5,
	"PROCESSED":          6,
}

func (x TransactionState_TransactionStateType) String() string {
	return proto.EnumName(TransactionState_TransactionStateType_name, int32(x))
}

func (TransactionState_TransactionStateType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cbf437cff72f155d, []int{9, 0}
}

// The results of STF transaction processing
type TransactionReceipt_TransactionResult int32

const (
	TransactionReceipt_UNDEFINED          TransactionReceipt_TransactionResult = 0
	TransactionReceipt_UNKNOWN            TransactionReceipt_TransactionResult = 1
	TransactionReceipt_EXECUTED           TransactionReceipt_TransactionResult = 2
	TransactionReceipt_BAD_COUNTER        TransactionReceipt_TransactionResult = 3
	TransactionReceipt_RUNTIME_EXCEPTION  TransactionReceipt_TransactionResult = 4
	TransactionReceipt_INSUFFICIENT_GAS   TransactionReceipt_TransactionResult = 5
	TransactionReceipt_INSUFFICIENT_FUNDS TransactionReceipt_TransactionResult = 6
)

var TransactionReceipt_TransactionResult_name = map[int32]string{
	0: "UNDEFINED",
	1: "UNKNOWN",
	2: "EXECUTED",
	3: "BAD_COUNTER",
	4: "RUNTIME_EXCEPTION",
	5: "INSUFFICIENT_GAS",
	6: "INSUFFICIENT_FUNDS",
}

var TransactionReceipt_TransactionResult_value = map[string]int32{
	"UNDEFINED":          0,
	"UNKNOWN":            1,
	"EXECUTED":           2,
	"BAD_COUNTER":        3,
	"RUNTIME_EXCEPTION":  4,
	"INSUFFICIENT_GAS":   5,
	"INSUFFICIENT_FUNDS": 6,
}

func (x TransactionReceipt_TransactionResult) String() string {
	return proto.EnumName(TransactionReceipt_TransactionResult_name, int32(x))
}

func (TransactionReceipt_TransactionResult) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cbf437cff72f155d, []int{10, 0}
}

type Transaction_TransactionType int32

const (
	Transaction_UNDEFINED       Transaction_TransactionType = 0
	Transaction_SIMPLE          Transaction_TransactionType = 1
	Transaction_ATX             Transaction_TransactionType = 2
	Transaction_APP             Transaction_TransactionType = 3
	Transaction_DEPLOY          Transaction_TransactionType = 4
	Transaction_DEPLOY_TEMPLATE Transaction_TransactionType = 5
)

var Transaction_TransactionType_name = map[int32]string{
	0: "UNDEFINED",
	1: "SIMPLE",
	2: "ATX",
	3: "APP",
	4: "DEPLOY",
	5: "DEPLOY_TEMPLATE",
}

var Transaction_TransactionType_value = map[string]int32{
	"UNDEFINED":       0,
	"SIMPLE":          1,
	"ATX":             2,
	"APP":             3,
	"DEPLOY":          4,
	"DEPLOY_TEMPLATE": 5,
}

func (x Transaction_TransactionType) String() string {
	return proto.EnumName(Transaction_TransactionType_name, int32(x))
}

func (Transaction_TransactionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cbf437cff72f155d, []int{11, 0}
}

type Layer_LayerStatus int32

const (
	Layer_UNDEFINED Layer_LayerStatus = 0
	Layer_UNKNOWN   Layer_LayerStatus = 1
	Layer_APPROVED  Layer_LayerStatus = 2
	Layer_CONFIRMED Layer_LayerStatus = 3
)

var Layer_LayerStatus_name = map[int32]string{
	0: "UNDEFINED",
	1: "UNKNOWN",
	2: "APPROVED",
	3: "CONFIRMED",
}

var Layer_LayerStatus_value = map[string]int32{
	"UNDEFINED": 0,
	"UNKNOWN":   1,
	"APPROVED":  2,
	"CONFIRMED": 3,
}

func (x Layer_LayerStatus) String() string {
	return proto.EnumName(Layer_LayerStatus_name, int32(x))
}

func (Layer_LayerStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cbf437cff72f155d, []int{13, 0}
}

type NodeError_NodeErrorType int32

const (
	NodeError_UNDEFINED         NodeError_NodeErrorType = 0
	NodeError_PANIC_UNSPECIFIED NodeError_NodeErrorType = 1
	NodeError_PANIC_SYNC        NodeError_NodeErrorType = 2
	NodeError_SIGNAL_SHUT_DOWN  NodeError_NodeErrorType = 3
)

var NodeError_NodeErrorType_name = map[int32]string{
	0: "UNDEFINED",
	1: "PANIC_UNSPECIFIED",
	2: "PANIC_SYNC",
	3: "SIGNAL_SHUT_DOWN",
}

var NodeError_NodeErrorType_value = map[string]int32{
	"UNDEFINED":         0,
	"PANIC_UNSPECIFIED": 1,
	"PANIC_SYNC":        2,
	"SIGNAL_SHUT_DOWN":  3,
}

func (x NodeError_NodeErrorType) String() string {
	return proto.EnumName(NodeError_NodeErrorType_name, int32(x))
}

func (NodeError_NodeErrorType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cbf437cff72f155d, []int{15, 0}
}

type NodeSyncStatus_NodeSyncStatusType int32

const (
	NodeSyncStatus_UNDEFINED   NodeSyncStatus_NodeSyncStatusType = 0
	NodeSyncStatus_SYNCED      NodeSyncStatus_NodeSyncStatusType = 1
	NodeSyncStatus_SYNCING     NodeSyncStatus_NodeSyncStatusType = 2
	NodeSyncStatus_NOT_SYNCING NodeSyncStatus_NodeSyncStatusType = 3
)

var NodeSyncStatus_NodeSyncStatusType_name = map[int32]string{
	0: "UNDEFINED",
	1: "SYNCED",
	2: "SYNCING",
	3: "NOT_SYNCING",
}

var NodeSyncStatus_NodeSyncStatusType_value = map[string]int32{
	"UNDEFINED":   0,
	"SYNCED":      1,
	"SYNCING":     2,
	"NOT_SYNCING": 3,
}

func (x NodeSyncStatus_NodeSyncStatusType) String() string {
	return proto.EnumName(NodeSyncStatus_NodeSyncStatusType_name, int32(x))
}

func (NodeSyncStatus_NodeSyncStatusType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cbf437cff72f155d, []int{16, 0}
}

type SimpleInt struct {
	Value                uint64   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleInt) Reset()         { *m = SimpleInt{} }
func (m *SimpleInt) String() string { return proto.CompactTextString(m) }
func (*SimpleInt) ProtoMessage()    {}
func (*SimpleInt) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbf437cff72f155d, []int{0}
}

func (m *SimpleInt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleInt.Unmarshal(m, b)
}
func (m *SimpleInt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleInt.Marshal(b, m, deterministic)
}
func (m *SimpleInt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleInt.Merge(m, src)
}
func (m *SimpleInt) XXX_Size() int {
	return xxx_messageInfo_SimpleInt.Size(m)
}
func (m *SimpleInt) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleInt.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleInt proto.InternalMessageInfo

func (m *SimpleInt) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type SimpleString struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleString) Reset()         { *m = SimpleString{} }
func (m *SimpleString) String() string { return proto.CompactTextString(m) }
func (*SimpleString) ProtoMessage()    {}
func (*SimpleString) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbf437cff72f155d, []int{1}
}

func (m *SimpleString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleString.Unmarshal(m, b)
}
func (m *SimpleString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleString.Marshal(b, m, deterministic)
}
func (m *SimpleString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleString.Merge(m, src)
}
func (m *SimpleString) XXX_Size() int {
	return xxx_messageInfo_SimpleString.Size(m)
}
func (m *SimpleString) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleString.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleString proto.InternalMessageInfo

func (m *SimpleString) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// a non-negative coin amount
type Amount struct {
	Value                uint64   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Amount) Reset()         { *m = Amount{} }
func (m *Amount) String() string { return proto.CompactTextString(m) }
func (*Amount) ProtoMessage()    {}
func (*Amount) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbf437cff72f155d, []int{2}
}

func (m *Amount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Amount.Unmarshal(m, b)
}
func (m *Amount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Amount.Marshal(b, m, deterministic)
}
func (m *Amount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Amount.Merge(m, src)
}
func (m *Amount) XXX_Size() int {
	return xxx_messageInfo_Amount.Size(m)
}
func (m *Amount) XXX_DiscardUnknown() {
	xxx_messageInfo_Amount.DiscardUnknown(m)
}

var xxx_messageInfo_Amount proto.InternalMessageInfo

func (m *Amount) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type AccountId struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountId) Reset()         { *m = AccountId{} }
func (m *AccountId) String() string { return proto.CompactTextString(m) }
func (*AccountId) ProtoMessage()    {}
func (*AccountId) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbf437cff72f155d, []int{3}
}

func (m *AccountId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountId.Unmarshal(m, b)
}
func (m *AccountId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountId.Marshal(b, m, deterministic)
}
func (m *AccountId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountId.Merge(m, src)
}
func (m *AccountId) XXX_Size() int {
	return xxx_messageInfo_AccountId.Size(m)
}
func (m *AccountId) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountId.DiscardUnknown(m)
}

var xxx_messageInfo_AccountId proto.InternalMessageInfo

func (m *AccountId) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

type Account struct {
	Address              *AccountId `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Counter              uint64     `protobuf:"varint,2,opt,name=counter,proto3" json:"counter,omitempty"`
	Balance              *Amount    `protobuf:"bytes,3,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbf437cff72f155d, []int{4}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetAddress() *AccountId {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Account) GetCounter() uint64 {
	if m != nil {
		return m.Counter
	}
	return 0
}

func (m *Account) GetBalance() *Amount {
	if m != nil {
		return m.Balance
	}
	return nil
}

type Reward struct {
	Layer         uint64  `protobuf:"varint,1,opt,name=layer,proto3" json:"layer,omitempty"`
	Total         *Amount `protobuf:"bytes,2,opt,name=total,proto3" json:"total,omitempty"`
	LayerReward   *Amount `protobuf:"bytes,3,opt,name=layer_reward,json=layerReward,proto3" json:"layer_reward,omitempty"`
	LayerComputed uint64  `protobuf:"varint,4,opt,name=layer_computed,json=layerComputed,proto3" json:"layer_computed,omitempty"`
	// tx_fee = total - layer_reward
	Coinbase             *AccountId `protobuf:"bytes,5,opt,name=coinbase,proto3" json:"coinbase,omitempty"`
	Smesher              *SmesherId `protobuf:"bytes,6,opt,name=smesher,proto3" json:"smesher,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Reward) Reset()         { *m = Reward{} }
func (m *Reward) String() string { return proto.CompactTextString(m) }
func (*Reward) ProtoMessage()    {}
func (*Reward) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbf437cff72f155d, []int{5}
}

func (m *Reward) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reward.Unmarshal(m, b)
}
func (m *Reward) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reward.Marshal(b, m, deterministic)
}
func (m *Reward) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reward.Merge(m, src)
}
func (m *Reward) XXX_Size() int {
	return xxx_messageInfo_Reward.Size(m)
}
func (m *Reward) XXX_DiscardUnknown() {
	xxx_messageInfo_Reward.DiscardUnknown(m)
}

var xxx_messageInfo_Reward proto.InternalMessageInfo

func (m *Reward) GetLayer() uint64 {
	if m != nil {
		return m.Layer
	}
	return 0
}

func (m *Reward) GetTotal() *Amount {
	if m != nil {
		return m.Total
	}
	return nil
}

func (m *Reward) GetLayerReward() *Amount {
	if m != nil {
		return m.LayerReward
	}
	return nil
}

func (m *Reward) GetLayerComputed() uint64 {
	if m != nil {
		return m.LayerComputed
	}
	return 0
}

func (m *Reward) GetCoinbase() *AccountId {
	if m != nil {
		return m.Coinbase
	}
	return nil
}

func (m *Reward) GetSmesher() *SmesherId {
	if m != nil {
		return m.Smesher
	}
	return nil
}

type TransactionId struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionId) Reset()         { *m = TransactionId{} }
func (m *TransactionId) String() string { return proto.CompactTextString(m) }
func (*TransactionId) ProtoMessage()    {}
func (*TransactionId) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbf437cff72f155d, []int{6}
}

func (m *TransactionId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionId.Unmarshal(m, b)
}
func (m *TransactionId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionId.Marshal(b, m, deterministic)
}
func (m *TransactionId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionId.Merge(m, src)
}
func (m *TransactionId) XXX_Size() int {
	return xxx_messageInfo_TransactionId.Size(m)
}
func (m *TransactionId) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionId.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionId proto.InternalMessageInfo

func (m *TransactionId) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

type SmesherId struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SmesherId) Reset()         { *m = SmesherId{} }
func (m *SmesherId) String() string { return proto.CompactTextString(m) }
func (*SmesherId) ProtoMessage()    {}
func (*SmesherId) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbf437cff72f155d, []int{7}
}

func (m *SmesherId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmesherId.Unmarshal(m, b)
}
func (m *SmesherId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmesherId.Marshal(b, m, deterministic)
}
func (m *SmesherId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmesherId.Merge(m, src)
}
func (m *SmesherId) XXX_Size() int {
	return xxx_messageInfo_SmesherId.Size(m)
}
func (m *SmesherId) XXX_DiscardUnknown() {
	xxx_messageInfo_SmesherId.DiscardUnknown(m)
}

var xxx_messageInfo_SmesherId proto.InternalMessageInfo

func (m *SmesherId) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

type TransactionFee struct {
	GasConsumed          uint64   `protobuf:"varint,1,opt,name=gas_consumed,json=gasConsumed,proto3" json:"gas_consumed,omitempty"`
	GasPrice             uint64   `protobuf:"varint,2,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionFee) Reset()         { *m = TransactionFee{} }
func (m *TransactionFee) String() string { return proto.CompactTextString(m) }
func (*TransactionFee) ProtoMessage()    {}
func (*TransactionFee) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbf437cff72f155d, []int{8}
}

func (m *TransactionFee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionFee.Unmarshal(m, b)
}
func (m *TransactionFee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionFee.Marshal(b, m, deterministic)
}
func (m *TransactionFee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionFee.Merge(m, src)
}
func (m *TransactionFee) XXX_Size() int {
	return xxx_messageInfo_TransactionFee.Size(m)
}
func (m *TransactionFee) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionFee.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionFee proto.InternalMessageInfo

func (m *TransactionFee) GetGasConsumed() uint64 {
	if m != nil {
		return m.GasConsumed
	}
	return 0
}

func (m *TransactionFee) GetGasPrice() uint64 {
	if m != nil {
		return m.GasPrice
	}
	return 0
}

// TransactionState is the "journey" of a tx from newly-submitted, to being
// rejected from or accepted into the mempool, to being included in the mesh (in a
// block), to (finally) being processed by the STF. It tells us nothing about the
// result of the processing.
type TransactionState struct {
	Id                   *TransactionId                        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	State                TransactionState_TransactionStateType `protobuf:"varint,2,opt,name=state,proto3,enum=spacemesh.TransactionState_TransactionStateType" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *TransactionState) Reset()         { *m = TransactionState{} }
func (m *TransactionState) String() string { return proto.CompactTextString(m) }
func (*TransactionState) ProtoMessage()    {}
func (*TransactionState) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbf437cff72f155d, []int{9}
}

func (m *TransactionState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionState.Unmarshal(m, b)
}
func (m *TransactionState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionState.Marshal(b, m, deterministic)
}
func (m *TransactionState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionState.Merge(m, src)
}
func (m *TransactionState) XXX_Size() int {
	return xxx_messageInfo_TransactionState.Size(m)
}
func (m *TransactionState) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionState.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionState proto.InternalMessageInfo

func (m *TransactionState) GetId() *TransactionId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *TransactionState) GetState() TransactionState_TransactionStateType {
	if m != nil {
		return m.State
	}
	return TransactionState_UNDEFINED
}

type TransactionReceipt struct {
	Id                   *TransactionId                       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Result               TransactionReceipt_TransactionResult `protobuf:"varint,2,opt,name=result,proto3,enum=spacemesh.TransactionReceipt_TransactionResult" json:"result,omitempty"`
	GasUsed              uint64                               `protobuf:"varint,3,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	Fee                  *Amount                              `protobuf:"bytes,4,opt,name=fee,proto3" json:"fee,omitempty"`
	LayerNumber          uint64                               `protobuf:"varint,5,opt,name=layer_number,json=layerNumber,proto3" json:"layer_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *TransactionReceipt) Reset()         { *m = TransactionReceipt{} }
func (m *TransactionReceipt) String() string { return proto.CompactTextString(m) }
func (*TransactionReceipt) ProtoMessage()    {}
func (*TransactionReceipt) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbf437cff72f155d, []int{10}
}

func (m *TransactionReceipt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionReceipt.Unmarshal(m, b)
}
func (m *TransactionReceipt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionReceipt.Marshal(b, m, deterministic)
}
func (m *TransactionReceipt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionReceipt.Merge(m, src)
}
func (m *TransactionReceipt) XXX_Size() int {
	return xxx_messageInfo_TransactionReceipt.Size(m)
}
func (m *TransactionReceipt) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionReceipt.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionReceipt proto.InternalMessageInfo

func (m *TransactionReceipt) GetId() *TransactionId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *TransactionReceipt) GetResult() TransactionReceipt_TransactionResult {
	if m != nil {
		return m.Result
	}
	return TransactionReceipt_UNDEFINED
}

func (m *TransactionReceipt) GetGasUsed() uint64 {
	if m != nil {
		return m.GasUsed
	}
	return 0
}

func (m *TransactionReceipt) GetFee() *Amount {
	if m != nil {
		return m.Fee
	}
	return nil
}

func (m *TransactionReceipt) GetLayerNumber() uint64 {
	if m != nil {
		return m.LayerNumber
	}
	return 0
}

// Simple coin transaction
// These fields are the immutable signed tx data which is part of the signed
// transaction body and do not include mutable data such as tx state or
// receipt.
type Transaction struct {
	Type                 Transaction_TransactionType `protobuf:"varint,1,opt,name=type,proto3,enum=spacemesh.Transaction_TransactionType" json:"type,omitempty"`
	Id                   *TransactionId              `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Sender               *AccountId                  `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	Fee                  *TransactionFee             `protobuf:"bytes,4,opt,name=fee,proto3" json:"fee,omitempty"`
	Timestamp            uint64                      `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Receiver             *AccountId                  `protobuf:"bytes,6,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Amount               *Amount                     `protobuf:"bytes,7,opt,name=amount,proto3" json:"amount,omitempty"`
	Counter              uint64                      `protobuf:"varint,8,opt,name=counter,proto3" json:"counter,omitempty"`
	Data                 []byte                      `protobuf:"bytes,9,opt,name=data,proto3" json:"data,omitempty"`
	SmesherId            *SmesherId                  `protobuf:"bytes,10,opt,name=smesher_id,json=smesherId,proto3" json:"smesher_id,omitempty"`
	PrevAtx              *TransactionId              `protobuf:"bytes,11,opt,name=prev_atx,json=prevAtx,proto3" json:"prev_atx,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbf437cff72f155d, []int{11}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetType() Transaction_TransactionType {
	if m != nil {
		return m.Type
	}
	return Transaction_UNDEFINED
}

func (m *Transaction) GetId() *TransactionId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Transaction) GetSender() *AccountId {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *Transaction) GetFee() *TransactionFee {
	if m != nil {
		return m.Fee
	}
	return nil
}

func (m *Transaction) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Transaction) GetReceiver() *AccountId {
	if m != nil {
		return m.Receiver
	}
	return nil
}

func (m *Transaction) GetAmount() *Amount {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *Transaction) GetCounter() uint64 {
	if m != nil {
		return m.Counter
	}
	return 0
}

func (m *Transaction) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Transaction) GetSmesherId() *SmesherId {
	if m != nil {
		return m.SmesherId
	}
	return nil
}

func (m *Transaction) GetPrevAtx() *TransactionId {
	if m != nil {
		return m.PrevAtx
	}
	return nil
}

type Block struct {
	Id                   []byte         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Transactions         []*Transaction `protobuf:"bytes,2,rep,name=transactions,proto3" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbf437cff72f155d, []int{12}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Block) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type Layer struct {
	Number               uint64            `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Status               Layer_LayerStatus `protobuf:"varint,2,opt,name=status,proto3,enum=spacemesh.Layer_LayerStatus" json:"status,omitempty"`
	Hash                 []byte            `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	Blocks               []*Block          `protobuf:"bytes,4,rep,name=blocks,proto3" json:"blocks,omitempty"`
	RootStateHash        []byte            `protobuf:"bytes,5,opt,name=root_state_hash,json=rootStateHash,proto3" json:"root_state_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Layer) Reset()         { *m = Layer{} }
func (m *Layer) String() string { return proto.CompactTextString(m) }
func (*Layer) ProtoMessage()    {}
func (*Layer) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbf437cff72f155d, []int{13}
}

func (m *Layer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Layer.Unmarshal(m, b)
}
func (m *Layer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Layer.Marshal(b, m, deterministic)
}
func (m *Layer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Layer.Merge(m, src)
}
func (m *Layer) XXX_Size() int {
	return xxx_messageInfo_Layer.Size(m)
}
func (m *Layer) XXX_DiscardUnknown() {
	xxx_messageInfo_Layer.DiscardUnknown(m)
}

var xxx_messageInfo_Layer proto.InternalMessageInfo

func (m *Layer) GetNumber() uint64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Layer) GetStatus() Layer_LayerStatus {
	if m != nil {
		return m.Status
	}
	return Layer_UNDEFINED
}

func (m *Layer) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Layer) GetBlocks() []*Block {
	if m != nil {
		return m.Blocks
	}
	return nil
}

func (m *Layer) GetRootStateHash() []byte {
	if m != nil {
		return m.RootStateHash
	}
	return nil
}

type NodeStatus struct {
	KnownPeers           uint64   `protobuf:"varint,1,opt,name=known_peers,json=knownPeers,proto3" json:"known_peers,omitempty"`
	MinPeers             uint64   `protobuf:"varint,2,opt,name=min_peers,json=minPeers,proto3" json:"min_peers,omitempty"`
	MaxPeers             uint64   `protobuf:"varint,3,opt,name=max_peers,json=maxPeers,proto3" json:"max_peers,omitempty"`
	IsSynced             bool     `protobuf:"varint,4,opt,name=is_synced,json=isSynced,proto3" json:"is_synced,omitempty"`
	SyncedLayer          uint64   `protobuf:"varint,5,opt,name=synced_layer,json=syncedLayer,proto3" json:"synced_layer,omitempty"`
	CurrentLayer         uint64   `protobuf:"varint,6,opt,name=current_layer,json=currentLayer,proto3" json:"current_layer,omitempty"`
	VerifiedLayer        uint64   `protobuf:"varint,7,opt,name=verified_layer,json=verifiedLayer,proto3" json:"verified_layer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeStatus) Reset()         { *m = NodeStatus{} }
func (m *NodeStatus) String() string { return proto.CompactTextString(m) }
func (*NodeStatus) ProtoMessage()    {}
func (*NodeStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbf437cff72f155d, []int{14}
}

func (m *NodeStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeStatus.Unmarshal(m, b)
}
func (m *NodeStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeStatus.Marshal(b, m, deterministic)
}
func (m *NodeStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeStatus.Merge(m, src)
}
func (m *NodeStatus) XXX_Size() int {
	return xxx_messageInfo_NodeStatus.Size(m)
}
func (m *NodeStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeStatus.DiscardUnknown(m)
}

var xxx_messageInfo_NodeStatus proto.InternalMessageInfo

func (m *NodeStatus) GetKnownPeers() uint64 {
	if m != nil {
		return m.KnownPeers
	}
	return 0
}

func (m *NodeStatus) GetMinPeers() uint64 {
	if m != nil {
		return m.MinPeers
	}
	return 0
}

func (m *NodeStatus) GetMaxPeers() uint64 {
	if m != nil {
		return m.MaxPeers
	}
	return 0
}

func (m *NodeStatus) GetIsSynced() bool {
	if m != nil {
		return m.IsSynced
	}
	return false
}

func (m *NodeStatus) GetSyncedLayer() uint64 {
	if m != nil {
		return m.SyncedLayer
	}
	return 0
}

func (m *NodeStatus) GetCurrentLayer() uint64 {
	if m != nil {
		return m.CurrentLayer
	}
	return 0
}

func (m *NodeStatus) GetVerifiedLayer() uint64 {
	if m != nil {
		return m.VerifiedLayer
	}
	return 0
}

type NodeError struct {
	Type                 NodeError_NodeErrorType `protobuf:"varint,1,opt,name=type,proto3,enum=spacemesh.NodeError_NodeErrorType" json:"type,omitempty"`
	Message              string                  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	StackTrace           string                  `protobuf:"bytes,3,opt,name=stack_trace,json=stackTrace,proto3" json:"stack_trace,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *NodeError) Reset()         { *m = NodeError{} }
func (m *NodeError) String() string { return proto.CompactTextString(m) }
func (*NodeError) ProtoMessage()    {}
func (*NodeError) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbf437cff72f155d, []int{15}
}

func (m *NodeError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeError.Unmarshal(m, b)
}
func (m *NodeError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeError.Marshal(b, m, deterministic)
}
func (m *NodeError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeError.Merge(m, src)
}
func (m *NodeError) XXX_Size() int {
	return xxx_messageInfo_NodeError.Size(m)
}
func (m *NodeError) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeError.DiscardUnknown(m)
}

var xxx_messageInfo_NodeError proto.InternalMessageInfo

func (m *NodeError) GetType() NodeError_NodeErrorType {
	if m != nil {
		return m.Type
	}
	return NodeError_UNDEFINED
}

func (m *NodeError) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *NodeError) GetStackTrace() string {
	if m != nil {
		return m.StackTrace
	}
	return ""
}

type NodeSyncStatus struct {
	Status               NodeSyncStatus_NodeSyncStatusType `protobuf:"varint,1,opt,name=status,proto3,enum=spacemesh.NodeSyncStatus_NodeSyncStatusType" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *NodeSyncStatus) Reset()         { *m = NodeSyncStatus{} }
func (m *NodeSyncStatus) String() string { return proto.CompactTextString(m) }
func (*NodeSyncStatus) ProtoMessage()    {}
func (*NodeSyncStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbf437cff72f155d, []int{16}
}

func (m *NodeSyncStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeSyncStatus.Unmarshal(m, b)
}
func (m *NodeSyncStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeSyncStatus.Marshal(b, m, deterministic)
}
func (m *NodeSyncStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeSyncStatus.Merge(m, src)
}
func (m *NodeSyncStatus) XXX_Size() int {
	return xxx_messageInfo_NodeSyncStatus.Size(m)
}
func (m *NodeSyncStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeSyncStatus.DiscardUnknown(m)
}

var xxx_messageInfo_NodeSyncStatus proto.InternalMessageInfo

func (m *NodeSyncStatus) GetStatus() NodeSyncStatus_NodeSyncStatusType {
	if m != nil {
		return m.Status
	}
	return NodeSyncStatus_UNDEFINED
}

func init() {
	proto.RegisterEnum("spacemesh.TransactionState_TransactionStateType", TransactionState_TransactionStateType_name, TransactionState_TransactionStateType_value)
	proto.RegisterEnum("spacemesh.TransactionReceipt_TransactionResult", TransactionReceipt_TransactionResult_name, TransactionReceipt_TransactionResult_value)
	proto.RegisterEnum("spacemesh.Transaction_TransactionType", Transaction_TransactionType_name, Transaction_TransactionType_value)
	proto.RegisterEnum("spacemesh.Layer_LayerStatus", Layer_LayerStatus_name, Layer_LayerStatus_value)
	proto.RegisterEnum("spacemesh.NodeError_NodeErrorType", NodeError_NodeErrorType_name, NodeError_NodeErrorType_value)
	proto.RegisterEnum("spacemesh.NodeSyncStatus_NodeSyncStatusType", NodeSyncStatus_NodeSyncStatusType_name, NodeSyncStatus_NodeSyncStatusType_value)
	proto.RegisterType((*SimpleInt)(nil), "spacemesh.SimpleInt")
	proto.RegisterType((*SimpleString)(nil), "spacemesh.SimpleString")
	proto.RegisterType((*Amount)(nil), "spacemesh.Amount")
	proto.RegisterType((*AccountId)(nil), "spacemesh.AccountId")
	proto.RegisterType((*Account)(nil), "spacemesh.Account")
	proto.RegisterType((*Reward)(nil), "spacemesh.Reward")
	proto.RegisterType((*TransactionId)(nil), "spacemesh.TransactionId")
	proto.RegisterType((*SmesherId)(nil), "spacemesh.SmesherId")
	proto.RegisterType((*TransactionFee)(nil), "spacemesh.TransactionFee")
	proto.RegisterType((*TransactionState)(nil), "spacemesh.TransactionState")
	proto.RegisterType((*TransactionReceipt)(nil), "spacemesh.TransactionReceipt")
	proto.RegisterType((*Transaction)(nil), "spacemesh.Transaction")
	proto.RegisterType((*Block)(nil), "spacemesh.Block")
	proto.RegisterType((*Layer)(nil), "spacemesh.Layer")
	proto.RegisterType((*NodeStatus)(nil), "spacemesh.NodeStatus")
	proto.RegisterType((*NodeError)(nil), "spacemesh.NodeError")
	proto.RegisterType((*NodeSyncStatus)(nil), "spacemesh.NodeSyncStatus")
}

func init() { proto.RegisterFile("spacemesh/types.proto", fileDescriptor_cbf437cff72f155d) }

var fileDescriptor_cbf437cff72f155d = []byte{
	// 1279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0xdd, 0x6e, 0xdb, 0x36,
	0x14, 0x9e, 0xff, 0x64, 0xeb, 0xc8, 0x76, 0x14, 0x2e, 0x2d, 0x54, 0xb4, 0x58, 0x5b, 0x75, 0xed,
	0x32, 0xb4, 0x48, 0x8b, 0xb4, 0xd8, 0x45, 0xef, 0x5c, 0x59, 0x4e, 0xb5, 0x25, 0xb2, 0x20, 0xc9,
	0x5b, 0x8b, 0x5d, 0x08, 0x8c, 0xc4, 0x26, 0x42, 0x6d, 0xc9, 0x10, 0xe5, 0x34, 0xb9, 0x2b, 0x30,
	0x6c, 0x57, 0xbb, 0xdb, 0x33, 0xec, 0x45, 0xf6, 0x1a, 0x7b, 0x8c, 0xbd, 0xc0, 0x40, 0x8a, 0x56,
	0x64, 0xc7, 0x69, 0xb7, 0x1b, 0x81, 0x3c, 0xe7, 0x3b, 0x1f, 0xc9, 0x73, 0x0e, 0x3f, 0x0a, 0x6e,
	0xd0, 0x39, 0x0e, 0xc9, 0x8c, 0xd0, 0xd3, 0xa7, 0xf9, 0xc5, 0x9c, 0xd0, 0xbd, 0x79, 0x96, 0xe6,
	0x29, 0x92, 0x4b, 0xb3, 0x7e, 0x1f, 0x64, 0x2f, 0x9e, 0xcd, 0xa7, 0xc4, 0x4a, 0x72, 0xb4, 0x03,
	0xad, 0x33, 0x3c, 0x5d, 0x10, 0xad, 0x76, 0xaf, 0xb6, 0xdb, 0x74, 0x8b, 0x89, 0xfe, 0x35, 0x74,
	0x0b, 0x88, 0x97, 0x67, 0x71, 0x72, 0xb2, 0x8a, 0x92, 0x97, 0xa8, 0xaf, 0x40, 0x1a, 0xcc, 0xd2,
	0xc5, 0xb5, 0x2c, 0x0f, 0x41, 0x1e, 0x84, 0x21, 0x03, 0x58, 0x11, 0xd2, 0xa0, 0x8d, 0xa3, 0x28,
	0x23, 0x94, 0x72, 0x50, 0xd7, 0x5d, 0x4e, 0xf5, 0x8f, 0x35, 0x68, 0x0b, 0x1c, 0xda, 0x5b, 0x45,
	0x29, 0xfb, 0x3b, 0x7b, 0xe5, 0xc6, 0xf7, 0x4a, 0xb2, 0x32, 0x96, 0xb1, 0x72, 0x1b, 0xc9, 0xb4,
	0x3a, 0x5f, 0x7a, 0x39, 0x45, 0x8f, 0xa1, 0x7d, 0x8c, 0xa7, 0x38, 0x09, 0x89, 0xd6, 0xe0, 0x4c,
	0xdb, 0x55, 0x26, 0xbe, 0x6d, 0x77, 0x89, 0xd0, 0x7f, 0xab, 0x83, 0xe4, 0x92, 0x0f, 0x38, 0x8b,
	0xd8, 0x51, 0xa6, 0xf8, 0x82, 0x64, 0xcb, 0xa3, 0xf0, 0x09, 0xfa, 0x06, 0x5a, 0x79, 0x9a, 0xe3,
	0x29, 0x5f, 0x65, 0x23, 0x57, 0xe1, 0x47, 0x2f, 0xa0, 0xcb, 0x23, 0x82, 0x8c, 0xd3, 0x5d, 0xbf,
	0xb6, 0xc2, 0x61, 0x62, 0xd1, 0x87, 0xd0, 0x2f, 0xa2, 0xc2, 0x74, 0x36, 0x5f, 0xe4, 0x24, 0xd2,
	0x9a, 0x7c, 0xf5, 0x1e, 0xb7, 0x1a, 0xc2, 0x88, 0x9e, 0x41, 0x27, 0x4c, 0xe3, 0xe4, 0x18, 0x53,
	0xa2, 0xb5, 0x3e, 0x91, 0x9e, 0x12, 0xc5, 0xf2, 0x49, 0x99, 0x93, 0x64, 0x9a, 0x74, 0x25, 0xc0,
	0x2b, 0x3c, 0x2c, 0x9f, 0x02, 0xa4, 0xdf, 0x85, 0x9e, 0x9f, 0xe1, 0x84, 0xe2, 0x30, 0x8f, 0xd3,
	0xc4, 0x8a, 0x50, 0x1f, 0xea, 0x71, 0x24, 0x2a, 0x56, 0x8f, 0x23, 0xfd, 0x36, 0xc8, 0x65, 0xd8,
	0x15, 0xa7, 0x03, 0xfd, 0x4a, 0xf4, 0x88, 0x10, 0x74, 0x1f, 0xba, 0x27, 0x98, 0x06, 0x61, 0x9a,
	0xd0, 0xc5, 0x8c, 0x44, 0x22, 0xa9, 0xca, 0x09, 0xa6, 0x86, 0x30, 0xa1, 0xdb, 0x20, 0x33, 0xc8,
	0x3c, 0x8b, 0x43, 0x22, 0x8a, 0xd8, 0x39, 0xc1, 0xd4, 0x61, 0x73, 0xfd, 0xf7, 0x3a, 0xa8, 0x15,
	0x4a, 0x2f, 0xc7, 0x39, 0x41, 0xbb, 0xe5, 0xb2, 0xca, 0xbe, 0x56, 0x39, 0xcf, 0xca, 0xce, 0xd9,
	0x86, 0xd0, 0x08, 0x5a, 0x94, 0x85, 0x70, 0xde, 0xfe, 0xfe, 0xb3, 0xcd, 0x60, 0xce, 0x7a, 0xc5,
	0xe0, 0x5f, 0xcc, 0x89, 0x5b, 0x84, 0xeb, 0xbf, 0xd6, 0x60, 0x67, 0x93, 0x1f, 0xf5, 0x40, 0x9e,
	0xd8, 0x43, 0x73, 0x64, 0xd9, 0xe6, 0x50, 0xfd, 0x02, 0x29, 0xd0, 0x9e, 0xd8, 0x3f, 0xd8, 0xe3,
	0x9f, 0x6c, 0xb5, 0x86, 0xba, 0xd0, 0x71, 0xcd, 0xef, 0x4d, 0xc3, 0x37, 0x87, 0x6a, 0x1d, 0xdd,
	0x04, 0x64, 0xd9, 0xde, 0x64, 0x34, 0xb2, 0x0c, 0xcb, 0xb4, 0xfd, 0x60, 0x34, 0xb1, 0x87, 0x9e,
	0xda, 0x40, 0x5b, 0xa0, 0x18, 0x63, 0x7b, 0x74, 0x68, 0x19, 0xbe, 0x65, 0x1f, 0xa8, 0x4d, 0xc6,
	0xe1, 0x98, 0xf6, 0x90, 0x4d, 0x5a, 0x8c, 0xdf, 0x71, 0xc7, 0x86, 0xe9, 0x79, 0xe6, 0x50, 0x95,
	0xf4, 0x8f, 0x0d, 0x40, 0x95, 0x7d, 0xb8, 0x24, 0x24, 0xf1, 0x3c, 0xff, 0x1f, 0x09, 0x39, 0x00,
	0x29, 0x23, 0x74, 0x31, 0xcd, 0x45, 0x46, 0x9e, 0x6e, 0x46, 0x0b, 0xe2, 0x55, 0x13, 0x0b, 0x73,
	0x45, 0x38, 0xba, 0x05, 0xac, 0x48, 0xc1, 0x82, 0x92, 0xa2, 0xc7, 0x9b, 0x6e, 0xfb, 0x04, 0xd3,
	0x09, 0x25, 0x11, 0x7a, 0x00, 0x8d, 0x77, 0x84, 0xf0, 0x0e, 0xde, 0xd8, 0xf9, 0xcc, 0xcb, 0x1a,
	0xa3, 0xe8, 0xf8, 0x64, 0x31, 0x3b, 0x26, 0x19, 0x6f, 0xe7, 0xa6, 0xb8, 0x14, 0x36, 0x37, 0xe9,
	0x7f, 0xd4, 0x60, 0xfb, 0xca, 0x06, 0x3e, 0x97, 0x71, 0xf3, 0x8d, 0x69, 0x4c, 0x8a, 0x8c, 0x6f,
	0x81, 0xf2, 0x6a, 0x30, 0x0c, 0x8c, 0xf1, 0xc4, 0xf6, 0x4d, 0x57, 0x6d, 0xa0, 0x1b, 0xb0, 0xed,
	0x4e, 0x6c, 0xdf, 0x3a, 0x32, 0x03, 0xf3, 0x8d, 0x61, 0x3a, 0xbe, 0x35, 0xb6, 0xd5, 0x26, 0xda,
	0x01, 0x75, 0xa5, 0x32, 0x07, 0x03, 0x4f, 0x6d, 0x5d, 0x53, 0x2f, 0x49, 0xff, 0xab, 0x09, 0x4a,
	0x65, 0x57, 0xe8, 0x25, 0x34, 0x99, 0xce, 0xf2, 0xec, 0xf7, 0xf7, 0x1f, 0x6d, 0xce, 0x67, 0x75,
	0xcc, 0xfb, 0x8a, 0xc7, 0x88, 0xba, 0xd5, 0xff, 0x43, 0xdd, 0x9e, 0x80, 0x44, 0x49, 0x12, 0x91,
	0x4c, 0x08, 0xca, 0xe6, 0x7b, 0x2f, 0x30, 0xe8, 0x71, 0xb5, 0x02, 0xb7, 0x36, 0x13, 0x8f, 0x08,
	0x29, 0x2a, 0x71, 0x07, 0xe4, 0x3c, 0x9e, 0x11, 0x9a, 0xe3, 0xd9, 0x5c, 0x94, 0xe1, 0xd2, 0xc0,
	0x24, 0x27, 0x63, 0xcd, 0x70, 0xb6, 0x51, 0x41, 0x2a, 0x92, 0xb3, 0x44, 0xa1, 0x6f, 0x41, 0xc2,
	0xbc, 0xd0, 0x5a, 0xfb, 0xba, 0x0e, 0x10, 0x80, 0xaa, 0x7a, 0x77, 0x56, 0xd5, 0x1b, 0x41, 0x33,
	0xc2, 0x39, 0xd6, 0x64, 0xae, 0x2d, 0x7c, 0x8c, 0x9e, 0x03, 0x08, 0x99, 0x0a, 0xe2, 0x48, 0x83,
	0x4f, 0xc8, 0x99, 0x4c, 0x4b, 0x89, 0x7a, 0x0e, 0x9d, 0x79, 0x46, 0xce, 0x02, 0x9c, 0x9f, 0x6b,
	0xca, 0x67, 0x12, 0xdd, 0x66, 0xc8, 0x41, 0x7e, 0xae, 0x07, 0xb0, 0xb5, 0x56, 0xb0, 0xf5, 0xb6,
	0x03, 0x90, 0x3c, 0xeb, 0xc8, 0x39, 0x34, 0xd5, 0x1a, 0x6a, 0x43, 0x63, 0xe0, 0xbf, 0x51, 0xeb,
	0x7c, 0xe0, 0x38, 0x6a, 0x83, 0x79, 0x87, 0xa6, 0x73, 0x38, 0x7e, 0xab, 0x36, 0xd1, 0x97, 0xb0,
	0x55, 0x8c, 0x03, 0xdf, 0x3c, 0x72, 0x0e, 0x07, 0xbe, 0xa9, 0xb6, 0x74, 0x0f, 0x5a, 0xaf, 0xa6,
	0x69, 0xf8, 0x7e, 0x5d, 0x41, 0xd1, 0x4b, 0xe8, 0xe6, 0x97, 0x2b, 0x53, 0xad, 0x7e, 0xaf, 0xb1,
	0xab, 0xec, 0xdf, 0xbc, 0xe6, 0x96, 0xae, 0x60, 0xf5, 0x5f, 0xea, 0xd0, 0x3a, 0xe4, 0xaf, 0xd5,
	0x4d, 0x90, 0xc4, 0xb5, 0x2a, 0xf4, 0x56, 0xcc, 0xd0, 0x0b, 0x90, 0x98, 0x9e, 0x2d, 0xa8, 0xb8,
	0xfd, 0x77, 0x2a, 0xbc, 0x3c, 0xb2, 0xf8, 0x7a, 0x1c, 0xe3, 0x0a, 0x2c, 0xab, 0xc5, 0x29, 0xa6,
	0xa7, 0xbc, 0xf3, 0xba, 0x2e, 0x1f, 0xa3, 0x5d, 0x90, 0x8e, 0xd9, 0x01, 0xa8, 0xd6, 0xe4, 0x3b,
	0x54, 0x2b, 0x4c, 0xfc, 0x64, 0xae, 0xf0, 0xa3, 0x47, 0xb0, 0x95, 0xa5, 0x69, 0x1e, 0x70, 0x21,
	0x0d, 0x38, 0x51, 0x8b, 0x13, 0xf5, 0x98, 0x99, 0x2b, 0xe9, 0x6b, 0x4c, 0x4f, 0xf5, 0x11, 0x28,
	0x95, 0xc5, 0x3f, 0x77, 0xcd, 0x07, 0x8e, 0xe3, 0x8e, 0x7f, 0xe4, 0xd7, 0xbc, 0x07, 0x32, 0x13,
	0x50, 0xcb, 0x3d, 0x32, 0x87, 0x6a, 0x43, 0xff, 0xa7, 0x06, 0x60, 0xa7, 0x11, 0x11, 0x3c, 0x77,
	0x41, 0x79, 0x9f, 0xa4, 0x1f, 0x92, 0x60, 0x4e, 0x48, 0x46, 0x45, 0x3e, 0x80, 0x9b, 0x1c, 0x66,
	0x61, 0xcf, 0xcf, 0x2c, 0x5e, 0xba, 0xc5, 0xf3, 0x33, 0x8b, 0x2b, 0x4e, 0x7c, 0x2e, 0x9c, 0x0d,
	0xe1, 0xc4, 0xe7, 0xa5, 0x33, 0xa6, 0x01, 0xbd, 0x48, 0x42, 0xf1, 0x5e, 0x77, 0xdc, 0x4e, 0x4c,
	0x3d, 0x3e, 0x67, 0xfa, 0x56, 0x78, 0x82, 0xe2, 0x6f, 0x42, 0xe8, 0x5b, 0x61, 0x2b, 0xaa, 0xf4,
	0x00, 0x7a, 0xe1, 0x22, 0xcb, 0x48, 0x92, 0x0b, 0x8c, 0xc4, 0x31, 0x5d, 0x61, 0x2c, 0x40, 0x0f,
	0xa1, 0x7f, 0x46, 0xb2, 0xf8, 0x5d, 0x5c, 0x32, 0xb5, 0x8b, 0x3f, 0x83, 0xa5, 0x95, 0xc3, 0xf4,
	0xbf, 0x6b, 0x20, 0xb3, 0x53, 0x9b, 0x59, 0x96, 0x66, 0xe8, 0xbb, 0x15, 0x4d, 0xd2, 0x2b, 0xb5,
	0x29, 0x31, 0x97, 0xa3, 0x8a, 0x1e, 0x69, 0xd0, 0x9e, 0x11, 0x4a, 0xf1, 0x49, 0xf1, 0x60, 0xca,
	0xee, 0x72, 0xca, 0xd2, 0x48, 0x73, 0x1c, 0xbe, 0x0f, 0xf2, 0x0c, 0x8b, 0x3f, 0x2a, 0xd9, 0x05,
	0x6e, 0xf2, 0x99, 0x45, 0xff, 0x19, 0x7a, 0x2b, 0x8c, 0xeb, 0x05, 0xbc, 0x01, 0xdb, 0xce, 0xc0,
	0xb6, 0x8c, 0x60, 0x62, 0x7b, 0x8e, 0x69, 0x58, 0x23, 0xcb, 0x1c, 0xaa, 0x35, 0xd4, 0x07, 0x28,
	0xcc, 0xde, 0x5b, 0xdb, 0x50, 0xeb, 0x4c, 0x8b, 0x3d, 0xeb, 0xc0, 0x1e, 0x1c, 0x06, 0xde, 0xeb,
	0x89, 0x1f, 0x0c, 0x59, 0xc1, 0x1b, 0xfa, 0x9f, 0x35, 0xe8, 0xf3, 0x9a, 0x5e, 0x24, 0xa1, 0xa8,
	0xeb, 0xb0, 0x6c, 0xe5, 0xe2, 0x90, 0x4f, 0xd6, 0x0e, 0x79, 0x09, 0x5d, 0x9b, 0xf2, 0xe3, 0x8a,
	0x58, 0xfd, 0x08, 0xd0, 0x55, 0xef, 0xa6, 0xbb, 0xfe, 0xd6, 0x36, 0xf8, 0x7e, 0x15, 0x68, 0xb3,
	0x31, 0x7b, 0x9c, 0xf9, 0x03, 0x63, 0x8f, 0xfd, 0x60, 0x69, 0x68, 0x1c, 0x4b, 0xfc, 0x5f, 0xfb,
	0xf9, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x95, 0xe1, 0x69, 0x61, 0x84, 0x0b, 0x00, 0x00,
}
