name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker meta dash
        id: meta_dash
        uses: docker/metadata-action@v4
        with:
          images: spacemeshos/dash-backend

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v2
        with:
          context: .
          repository: spacemeshos/dash-backend
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta_dash.outputs.tags }}